### ISSUE TITLE
Create examples for external recommender

### ISSUE THREAD

**Issue by Rentier** [inception-project/inception#366] opened 2018-07-02 12:10 UTC
**Is your feature request related to a problem? Please describe.**
Right now, getting started with the external recommender is difficult. It would be nice to have easy-to-use examples for common use cases and frameworks.

**Describe the solution you'd like**
Create example external recommender in Java and Python (sklearn). The choice of possible examples is limited by which languages can read/write CAS XMI.

- [ ] Create spacy example
- [ ] Add example project to INCEpTION website

**Comment by reckart** [comment] 2018-12-18 14:57
Duplicate of https://github.com/inception-project/inception-project.github.io/pull/16

**Closed by reckart** 2018-12-18 14:57 UTC
Labels: Module: Recommender, 🆕Enhancement
