### ISSUE TITLE
String Recomender sharing labels between unrelated Layers

### ISSUE THREAD

**Issue by david-waterworth** [inception-project/inception#2521] opened 2021-07-29 23:13 UTC
**Describe the bug**
I created a layer with a tagset and string recommender, added some (NER) labels and then deleted the layer and all annotations. 
I then created a new layer with a new tagset and a new string recommended (the names of each were different, but the feature names and types weren't). I added new annotations (different policy, i.e. different tagset) 

The string recommender then immediately started adding recommendations for tags from the old (deleted) tagset. It seems that the learned gazetteer from the first string matcher is being reused for the second. Possibly since both layers shared similar feature names/types (i.e. value).

It may be desirable to have this as an option, but I don't think it should be the default, I think a gazetteer should use (layer, feature, type) rather than (feature, type) to matches, and a new string matcher should have an empty gazetteer.

**Comment by reckart** [comment] 2021-07-30 01:16
Hm, that sounds odd. Recommenders are configured for specifically for a layer/feature. No data should "leak" from one recommender to another.

**Comment by reckart** [comment] 2021-08-10 19:08
I am having trouble reproducing this effect. Can you provide a step-by-step guide or a video how to provoke this?

**Comment by reckart** [comment] 2021-12-04 12:12
Closing as I could not reproduce it and there was no further feedback.

**Closed by reckart** 2021-12-04 12:12 UTC
Labels: Module: Recommender, Support request
