### ISSUE TITLE
Allow option to update existing annotation provided by recommender

### ISSUE THREAD

**Issue by thak123** [inception-project/inception#1632] opened 2020-03-10 20:50 UTC
I am trying to update annotations provided to my by recommender. The spans are always having one word extra or one word less.
I
**Describe the solution you'd like**
I want the option to update the annotation span 

**Describe alternatives you've considered**
I delete the existing annotations and re annotate the spans

**Comment by reckart** [comment] 2020-03-10 21:07
I think this would require changes to the upstream validator sub-system to allow ensuring that the new boundaries would not violate e.g. stacking and similar behaviors.

A simpler approach would just delete / re-add - but that would mean losing any relations attached to the resized span. So not sure if that would be even worth going for as an intermediate solution.

**Comment by reckart** [comment] 2023-01-04 18:21
Duplicate of https://github.com/inception-project/inception/issues/283

**Closed** 2023-01-04 18:21 UTC
Labels: ⭐️ Enhancement, Module: Annotation
