### ISSUE TITLE
Swagger does not work in https 

### ISSUE THREAD

**Issue by ofersabo** [inception-project/inception#2507] opened 2021-07-25 09:41 UTC
**Describe the bug**
Recently we moved our INCEpTION tool to HTTPS deployment. 
Then we notice that the swagger isn't working. We believe the is that Swagger sends its request in HTTP.
We'd like to reconfigure Swagger to work on an HTTPS deployment.

**To Reproduce**
Install the tool on HTTPS deployment and try to use the swagger. 

**Screenshots**
Here is the error that swagger returns 
![image](https://user-images.githubusercontent.com/31179968/126894728-f552a32c-0ad7-4946-afa3-e6102fda4308.png)

**Comment by reckart** [comment] 2021-07-25 20:16
Did you follow any particular documentation / howto for running on HTTPS? 

We have INCEpTION running using a reverse proxy-based HTTPS setup and I was able to access the Swagger UI as well as to submit a "list projects" request through the Swagger UI.

**Comment by reckart** [comment] 2021-08-03 15:55
@ofersabo any feedback?

**Comment by ofersabo** [comment] 2021-08-03 17:41
Hi @reckart 

Thanks for the follow-up.

To answer that I'd need help from my friend who made INCEpTION run in HTTPS.

**Comment by reckart** [comment] 2021-08-29 16:04
@ofersabo still no more info? Or could the problem be resolved? In either case, I'd be inclined to close the issue as I cannot reproduce the issue either.

**Comment by ofersabo** [comment] 2021-08-30 07:27
Hi @reckart 

The problem isn't resolved, we are still waiting for some help on this from our DevOps. 
Let me remind them. Meanwhile, you can close this issue and I'll reopen (can I?) once I've more information.

**Comment by reckart** [comment] 2021-11-30 22:05
Assuming the that issue was resolved as there was no more feedback and thus closing the issue.

**Closed by reckart** 2021-11-30 22:05 UTC
Labels: Support request
