### ISSUE TITLE
Annotations crossing a line border and linking to a knowledge base are not possible

### ISSUE THREAD

**Issue by Wolkenstein** [inception-project/inception#1600] opened 2020-01-21 11:44 UTC
**Decription**
Annotations crossing a line border and linking to a knowledge base are not possible. 
(http://Error ''Lexical error at line [..], column [..]. Encountered "\n" ([...]) after "[...]")

**Reproduce**
1. Create Layer: Type 'Span'
2. Add Tagset Type KB:Concept/Instance/Property to Layer
3. Link with local Knowledge Base
4. Open multiline Text
5. View line-oriented
6. Annotate crossing a line border
7. Try to chooce a concept of the Knowledge Base
--> Error

**Expected behavior**
Annotation spanning multiple lines and linking to a concept

**Screenshots**
![inception_error](https://user-images.githubusercontent.com/11350659/72802269-aebc2100-3c4b-11ea-9a1c-20e842b6ed7c.png)

**Please complete the following information:**
 - INCEpTION -- 0.14.2 (2019-12-31 16:20:49, build a44b4c76b19fcc3d0a58e75a82aafdd96a564500)
 - OS: Linux (Docker Container)
 - Browser: Chrome

**Comment by reckart** [comment] 2020-01-21 12:58
The cleanup of the query strings has been improved in/around https://github.com/inception-project/inception/commit/781ea43bd1c021e0f88a3030f3144ea461fe3274 - so I think this should be fixed in 0.15.x - but needs verification.

**Comment by reckart** [comment] 2020-03-10 15:18
@UWinch @jcklie any chance this could be verified/fixed for 0.15?

**Comment by jcklie** [comment] 2020-03-16 10:26
I tried it with dbpedia and a local wine ontology, both worked for me with the following document imported as plain text:

```
I am a test.
I am a second 
test. 
I am a third 
test and i am longer
```

**Comment by reckart** [comment] 2020-03-17 14:08
Cannot reproduce with latest version, assuming it to be fixed.

**Comment by almasch** [comment] 2021-02-01 10:15
This bug also occurs at my installation.
INCEpTION -- 0.17.4 (2021-01-13 23:39:05, build 2bb5cd9e078e9dca5ef29d40d8381c44ee9b1431)
OS: Ubuntu Linux (Docker Container)
Browser: macOS Safari, Firefox


It works with a local wine ontology but with no locally imported ontologies created by webprotege. The problem can be reproduced by:
1. creating a local Knowledge Base and no import of any ontology
2. go to Dashboard->Knowledge Base and select this Knowledge Base
3. Create some new concepts.

When using this Knowledge Base for annotate  a multi line sentence the error occurs. 
 Error: Annotation covers multiple sentences, limit your annotation to single sentence!

Server Log contains:
2021-02-01 09:52:11 INFO [user] AnnotationSchemaServiceImpl - Upgraded CAS of user [user] for document [doc1.txt](16) in project [Bug Report inception](4)
2021-02-01 09:52:18 INFO [user] ApplicationPageBase - user: The [Knowlege Base] annotation has been deleted.
2021-02-01 09:52:21 ERROR [user] ConceptFeatureEditor - An error occurred while retrieving entity candidates
org.eclipse.rdf4j.query.MalformedQueryException: Lexical error at line 3, column 53.  Encountered: "\n" (10), after : "\"This is a sentence"
	at org.eclipse.rdf4j.query.parser.sparql.SPARQLParser.parseQuery(SPARQLParser.java:184) ~[rdf4j-queryparser-sparql-2.5.1-inception-1.jar!/:2.5.1-inception-1+47c031e]
	at org.eclipse.rdf4j.query.parser.QueryParserUtil.parseQuery(QueryParserUtil.java:93) ~[rdf4j-client-2.5.1-inception-1.jar!/:2.5.1-inception-1+47c031e]
	at org.eclipse.rdf4j.query.parser.QueryParserUtil.parseTupleQuery(QueryParserUtil.java:108) ~[rdf4j-client-2.5.1-inception-1.jar!/:2.5.1-inception-1+47c031e]
	at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.prepareTupleQuery(SailRepositoryConnection.java:211) ~[rdf4j-repository-sail-2.5.1-inception-1.jar!/:2.5.1-inception-1+8dce3bc]

[.....]


Caused by: org.eclipse.rdf4j.query.parser.sparql.ast.TokenMgrError: Lexical error at line 3, column 53.  Encountered: "\n" (10), after : "\"This is a sentence"
	at org.eclipse.rdf4j.query.parser.sparql.ast.SyntaxTreeBuilderTokenManager.getNextToken(SyntaxTreeBuilderTokenManager.java:3124) ~[rdf4j-queryparser-sparql-2.5.1-inception-1.jar!/:2.5.1-inception-1+47c031e]
	at org.eclipse.rdf4j.query.parser.sparql.ast.SyntaxTreeBuilder.jj_ntk(SyntaxTreeBuilder.java:10209) ~[rdf4j-queryparser-sparql-2.5.1-inception-1.jar!/:2.5.1-inception-1+47c031e]
	at org.eclipse.rdf4j.query.parser.sparql.ast.SyntaxTreeBuilder.BindingSet(SyntaxTreeBuilder.java:1318) ~[rdf4j-queryparser-sparql-2.5.1-inception-1.jar!/:2.5.1-inception-1+47c031e]
[...]

**Comment by almasch** [comment] 2021-02-01 10:18
<img width="913" alt="Bildschirmfoto 2021-02-01 um 10 55 09" src="https://user-images.githubusercontent.com/11016436/106445289-1fad3000-647f-11eb-8978-aac904dc90f8.png">

**Comment by reckart** [comment] 2021-02-01 20:23
Thanks for reporting.

**Closed** 2021-02-02 17:33 UTC
Labels: Module: Entity Linking, 🐛Bug

**Comment by reckart** [comment] 2021-02-03 19:09
@almasch while waiting for the bugfix release, you should be able to avoid the issue by setting them **Full text search mode** on your KB to `...lucenesail#matches`.

**Comment by reckart** [comment] 2021-02-03 19:09
See also #1977
