### ISSUE TITLE
Link label showing up as empty Layer name

### ISSUE THREAD

**Issue by GiantEnemyCrab** [inception-project/inception#3654] opened 2022-12-21 23:02 UTC
For some reason, even if link role name is specified in the annotation, it is somehow showing up as empty layer name.
![link_name_empty](https://user-images.githubusercontent.com/1326079/209018868-cecfb792-e7d7-45f4-925b-1021452e1d89.PNG)

## To reproduce from just-released-26.2 version ##
1. New basic project (span/relation)
2. Delete relation layer
3. Add link feature to span layer. I named the feature as "Links". The link type is "Link: Span", Tagset is "Relation labels".
4. Then begin to annotate tags and links. Tags work fine, they show the tag name, but Links don't because it will show empty `{Span}` text, like the screen shot above. Below screen shot is Layer config. I used "tag1", "tag2", etc as tag names and "link1", "link2" as Link role names.

![link_name_empty_settings](https://user-images.githubusercontent.com/1326079/209019119-c1ca8487-7dc0-4f1b-850b-b6f5da78f2a8.PNG)

**Comment by reckart** [comment] 2022-12-22 07:29
Thanks for the report. It seems to be a duplicate of https://github.com/inception-project/inception/issues/3650 - the issue is already fixed, release coming soon.

**Closed** 2022-12-22 09:07 UTC
Labels: 🐛Bug, Module: Annotation

**Comment by GiantEnemyCrab** [comment] 2022-12-22 14:42
Thank you so much for the fix! Much appreciated!
