### ISSUE TITLE
Document indexed twice

### ISSUE THREAD

**Issue by betoboullosa** [inception-project/inception#444] opened 2018-08-09 14:03 UTC
**Describe the bug**
When adding a new document in a project that still does not have an index, the document is indexed twice. This happens because the creation of a new index indexes all project documents, and, at the moment the new document indexing is called through SearchService.afterDocumentCreate, the document is already present in the project. 

**To Reproduce**
This error is reproduced in the MtasDocumentIndexTest.testRawTextQuery test.

**Expected behavior**
When a new document is added to a project that still does not have an index, it should not be indexed again. 

**Please complete the following information:**
 - Version and build ID: 0.5.0-SNAPSHOT

**Comment by betoboullosa** [comment] 2018-08-13 14:00
Fixed in https://github.com/inception-project/inception/pull/456/commits/87ea527019e8e2b90e51a96a789c848e661c76c6

**Comment by reckart** [comment] 2018-08-13 18:37
See https://github.com/inception-project/inception/commit/87ea527019e8e2b90e51a96a789c848e661c76c6#r30058995

The change in 87ea527 unfixes a previous fix. There must be a better approach.

Please do not commit directly to the branches and stick to doing PRs unless surgery on the git repository is required.

**Comment by reckart** [comment] 2018-08-13 18:39
Never mind, I found the PR: https://github.com/inception-project/inception/pull/456

@naveen2507 are you really sure you wanted to approve this change?

**Comment by naveen2507** [comment] 2018-08-13 19:25
Yeah @reckart. The issue couldn't be reproduced in 0.5.0 due to the code at line https://github.com/inception-project/inception/blob/87ea527019e8e2b90e51a96a789c848e661c76c6/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java#L631

This code wasn't there in 0.4.2 , so issue has been addressed here.

**Comment by reckart** [comment] 2018-08-13 19:37
@naveen2507 ok, great. Then closing this issue again.

**Closed by reckart** 2018-08-13 19:37 UTC
Labels: Module: Project Search, 🐛Bug
