### ISSUE TITLE
Automatic (and manual) merging doesn't work

### ISSUE THREAD

**Issue by s2fische** [inception-project/inception#4852] opened 2024-06-05 15:43 UTC
Currently, no completely similar annotations are merged automatically at all, in both curation modes. Trying to manually merge them did also not work.

![1 Clipboard - 5  Juni 2024 15_06](https://github.com/inception-project/inception/assets/170112224/790a77d8-c802-4180-9cf7-9ab421e65b63)

**Please complete the following information:**
 - Version and build ID: 32.2 (2024-05-14 20:46:45, build 101ef65)
 - OS: Windows 10
 - Browser: Chrome

**Comment by reckart** [comment] 2024-06-05 15:47
As with https://github.com/inception-project/inception/issues/4822 it would be great if you could provide me with a project that allows me to reproduce this. You can send it privately by email.

**Comment by reckart** [comment] 2024-06-15 11:15
@bgittel @s2fische Thank you for providing data to investigate. Since we could both no longer reproduce the issue, I am closing this now as cannot-reproduce. If the problem re-appears, please comment or open another issue.

**Comment by s2fische** [comment] 2024-07-04 16:07
The problem re-appeared in another document:

![Screenshot 2024-07-03 151018](https://github.com/inception-project/inception/assets/170112224/d40eb184-d9f3-416f-aa91-58411f3ae5a8)

![Screenshot 2024-07-03 151358](https://github.com/inception-project/inception/assets/170112224/0e3019e5-786a-43ba-8e53-ad5f59d2398c)

![Screenshot 2024-07-03 151505](https://github.com/inception-project/inception/assets/170112224/1c029436-e193-4b8c-9180-976725e20025)

![Screenshot 2024-07-03 161512](https://github.com/inception-project/inception/assets/170112224/89d689c9-5ea5-4387-81fd-36cd0564b46c)

**Comment by reckart** [comment] 2024-07-04 19:28
Could you please try opening the JavaScript developer console of your browser and check if you see and error messages there when you view one of these sentenes?

**Comment by reckart** [comment] 2024-07-04 19:52
When you log out and log back in, does the problem persist?

When you restart the server, does the problem persist?

**Comment by reckart** [comment] 2024-07-19 14:05
<img width="814" alt="Screenshot 2024-07-19 at 11 00 09" src="https://github.com/user-attachments/assets/ba75bedc-91e0-4e29-a7c1-6b38ae1b16f2">

So, I have looked into this issue (see screenshot above). The problem ist that the system considers this configuration as being **stacked** - and stacked annotations are not merged by the default merge strategy. 

Currently, the system looks at the configuration and sees two links between the annotations labeled `FIGUR...` and `eudämonistisch...` - each of which having a different role. So it says that the user can apparently not decide which role is correct for the relation between these endpoints and it will say it is stacked. The system calls this `LINK_ROLE_AS_LABEL` mode.

In principle, the system also supports another mode, namely `LINK_TARGET_AS_LABEL`. In this case, it would see two slots (`gewertete Entität` and `codierte Entität`) and see that their slot fillers agree and then merge.

Probably, the way that a link feature is treated (`LINK_TARGET_AS_LABEL` or `LINK_ROLE_AS_LABEL`)  should be configurable in the feature settings. However, doing this is quite a bit of refactoring.

**Comment by reckart** [comment] 2024-07-23 21:16
With https://github.com/inception-project/inception/issues/4956 you will be able to configure the multiplicity of link features. The multiplicity option **Target can be linked in multiple different roles** or **Target can be linked in multiple roles (same or different)** should both be able to deal with the scenario from the previous post and hopfully will be useable for you.

**Closed** 2024-07-23 21:17 UTC
Labels: Support request
