### ISSUE TITLE
Cannot invoke "org.eclipse.rdf4j.repository.Repository.getConnection()" because "repo" is null

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2400] opened 2021-06-20 19:19 UTC
**Describe the bug**

Unable to create token collection
Cannot invoke "org.eclipse.rdf4j.repository.Repository.getConnection()" because "repo" is null

**To Reproduce**
Open project 141 on blinky stable and annotate stuff I think.

**Expected behavior**
No error

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 0.20.0-rc-1 (2021-06-20 19:15:18, build 7a17ddc8)
 - OS: Windows
 - Browser: Chrome

**Additional context**

```
(129) for user [klie] to document [Emmanuel_Macron_QA.txt](8182) in project [COLING 2018 - Entity linking](141) - skipping recommender
Jun 20 21:11:21 blinky inception-stable.jar[8968]: java.lang.NullPointerException: Cannot invoke "org.eclipse.rdf4j.repository.Repository.getConnection()" because "repo" is null
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl.getConnection(KnowledgeBaseServiceImpl.java:444) ~[inception-kb-0.20.0-rc-1.jar!/:?]
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl.read(KnowledgeBaseServiceImpl.java:873) ~[inception-kb-0.20.0-rc-1.jar!/:?]
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl$$FastClassBySpringCGLIB$$77259834.invoke(<generated>) ~[inception-kb-0.20.0-rc-1.jar!/:?]
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.6.jar!/:5.3.6]
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.3.6.jar!/:5.3.6]
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl$$EnhancerBySpringCGLIB$$dbd42848.read(<generated>) ~[inception-kb-0.20.0-rc-1.jar!/:?]
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at de.tudarmstadt.ukp.inception.conceptlinking.recommender.NamedEntityLinker.readCandidates(NamedEntityLinker.java:142) ~[inception-concept-linking-0.20.0-rc-1.jar!/:?]
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at de.tudarmstadt.ukp.inception.conceptlinking.recommender.NamedEntityLinker.predictSingle(NamedEntityLinker.java:120) ~[inception-concept-linking-0.20.0-rc-1.jar!/:?]
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at de.tudarmstadt.ukp.inception.conceptlinking.recommender.NamedEntityLinker.predict(NamedEntityLinker.java:97) ~[inception-concept-linking-0.20.0-rc-1.jar!/:?]
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at de.tudarmstadt.ukp.inception.recommendation.service.RecommendationServiceImpl.generateSuggestions(RecommendationServiceImpl.java:1477) ~[inception-recommendation-0.20.0-rc-1.jar!/:?]
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at de.tudarmstadt.ukp.inception.recommendation.service.RecommendationServiceImpl.computePredictions(RecommendationServiceImpl.java:1354) [inception-recommendation-0.20.0-rc-1.jar!/:?]
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at de.tudarmstadt.ukp.inception.recommendation.service.RecommendationServiceImpl$$FastClassBySpringCGLIB$$7b2c1577.invoke(<generated>) [inception-recommendation-0.20.0-rc-1.jar!/:?]
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.3.6.jar!/:5.3.6]
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) [spring-aop-5.3.6.jar!/:5.3.6]
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at de.tudarmstadt.ukp.inception.recommendation.service.RecommendationServiceImpl$$EnhancerBySpringCGLIB$$af1281f1.computePredictions(<generated>) [inception-recommendation-0.20.0-rc-1.jar!/:?]
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at de.tudarmstadt.ukp.inception.recommendation.tasks.PredictionTask.execute(PredictionTask.java:94) [inception-recommendation-0.20.0-rc-1.jar!/:?]
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at de.tudarmstadt.ukp.inception.scheduling.Task.run(Task.java:110) [inception-scheduling-0.20.0-rc-1.jar!/:?]
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
Jun 20 21:11:21 blinky inception-stable.jar[8968]:         at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by reckart** [comment] 2021-06-20 19:30
There is no KB with the id "pid-141-kbid-" on disk, that is why we get the exceptions.

**Comment by reckart** [comment] 2021-06-20 19:35
I think the problem is old and due to a broken project. We already got an NPE in that project back in February 2019 while trying to read the KB configuration. Maybe some power outage around that time?

```
2019-02-15 04:47:21,483 Unexpected error during project export
de.tudarmstadt.ukp.clarin.webanno.api.export.ProjectExportException: Project export failed
        at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl.exportProject(ProjectExportServiceImpl.java:204) ~[webanno-api-dao-3.5.2.jar!/:?]
        at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl.exportProject(ProjectExportServiceImpl.java:130) ~[webanno-api-dao-3.5.2.jar!/:?]
        at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl$$FastClassBySpringCGLIB$$3d43e16f.invoke(<generated>) ~[webanno-api-dao-3.5.2.jar!/:?]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) ~[spring-aop-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl$$EnhancerBySpringCGLIB$$202dc9f1.exportProject(<generated>) ~[webanno-api-dao-3.5.2.jar!/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:522) ~[wicket-ioc-8.1.0.jar!/:8.1.0]
        at com.sun.proxy.$Proxy162.exportProject(Unknown Source) ~[?:?]
        at de.tudarmstadt.ukp.clarin.webanno.ui.project.export.ProjectExportPanel$FileGenerator.run(ProjectExportPanel.java:409) [webanno-ui-project-3.5.2.jar!/:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl.getKnowledgeBaseConfig(KnowledgeBaseServiceImpl.java:365) ~[inception-kb-0.7.2.jar!/:?]
        at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl$$FastClassBySpringCGLIB$$77259834.invoke(<generated>) ~[inception-kb-0.7.2.jar!/:?]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684) ~[spring-aop-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl$$EnhancerBySpringCGLIB$$2c44d160.getKnowledgeBaseConfig(<generated>) ~[inception-kb-0.7.2.jar!/:?]
        at de.tudarmstadt.ukp.inception.kb.exporter.KnowledgeBaseExporter.exportData(KnowledgeBaseExporter.java:134) ~[inception-kb-0.7.2.jar!/:?]
        at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl.exportProject(ProjectExportServiceImpl.java:185) ~[webanno-api-dao-3.5.2.jar!/:?]
        ... 18 more
```

**Comment by reckart** [comment] 2021-06-20 19:40
Closing this one as evidence points towards the project already having been broken before the upgrade.

**Closed** 2021-06-20 21:04 UTC
Labels: Support request
