### ISSUE TITLE
Curate meta data annotations

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1659] opened 2020-04-07 12:21 UTC
**Is your feature request related to a problem? Please describe.**
Currently meta data annotations (document-level annotations) cannot be curated. It would be nice to integrate this feature into the curation sidebar.

**Comment by reckart** [comment] 2022-10-12 18:35
Closing as duplicate of https://github.com/inception-project/inception/issues/2702

**Closed by reckart** 2022-10-12 18:35 UTC
Labels: ⭐️ Enhancement, Module: Curation
