### ISSUE TITLE
Active learning broken - Concurrent change to the document

### ISSUE THREAD

**Issue by Rentier** [inception-project/inception#727] opened 2018-11-28 10:40 UTC
**Describe the bug**
When accepting annotations during active learning, an error is thrown:

`Unable to load data: IOException: There was a concurrent change to the document. Re-open the document to continue editing.`

**To Reproduce**
1. Create a new project
2. Import documents
3. Create string NER recommender
4. Annotate stuff until you see recommendations
5. Start active learning and accept things

**Expected behavior**
The recommendation turns into an annotation

**Screenshots**

**Please complete the following information:**
 - Version and build ID: 0.7.0-SNAPSHOT (2018-11-28 01:52:32, build 35f832474b3cadc0e2919d879c78458a64360780)
 - OS: Linux
 - Browser: Chrome

**Additional context**
Log message (cut):

```
2018-11-28 11:35:04 INFO [klie] EventRepositoryImpl - LoggedEvent [created=Wed Nov 28 11:35:04
 CET 2018, event=ActiveLearningRecommendationEvent, user=klie, project=115, document=575, deta
ils={"ann":{"addr":-1,"begin":716,"end":733,"type":"de.tudarmstadt.ukp.dkpro.core.api.ner.type
.NamedEntity","text":"Nicholas Thompson"},"annotationFeature":"value","userAction":"SHOWN","cu
rrentLabel":"PER","confidence":1.0,"recommenderId":108,"allLabels":"PER"}]
2018-11-28 11:35:04 ERROR [klie] BratAnnotationEditor - Unable to load data
java.io.IOException: There was a concurrent change to the document. Re-open the document to continue editing.
        at de.tudarmstadt.ukp.clarin.webanno.api.annotation.model.AnnotatorStateUtils.verifyAndUpdateDocumentTimestamp(AnnotatorStateUtils.java:33) ~[webanno-api-annotation-3.5.0-SNAPSHOT.jar!/:?]
        at de.tudarmstadt.ukp.clarin.webanno.ui.annotation.AnnotationPage.getEditorCas(AnnotationPage.java:422) ~[webanno-ui-annotation-3.5.0-SNAPSHOT.jar!/:?]
        at de.tudarmstadt.ukp.clarin.webanno.brat.annotation.BratAnnotationEditor.render(BratAnnotationEditor.java:657) [webanno-brat-3.5.0-SNAPSHOT.jar!/:?]
        at de.tudarmstadt.ukp.clarin.webanno.api.annotation.AnnotationEditorBase$RenderListener.onTargetRespond(AnnotationEditorBase.java:221) [webanno-api-annotation-3.5.0-SNAPSHOT.jar!/:?]
        at org.apache.wicket.ajax.AjaxRequestHandler.respond(AjaxRequestHandler.java:367) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:912) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:65) [wicket-request-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:283) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:253) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:221) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:262) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:204) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:286) [wicket-core-8.1.0.jar!/:8.1.0]
```

**Comment by reckart** [comment] 2018-11-28 10:44
Duplicate of #719 - and there is also already a PR awaiting approval: https://github.com/inception-project/inception/pull/720

**Comment by reckart** [comment] 2018-11-28 10:46
The 0.6.x branch should not be affected by this, at least as long as it is based on WebAnno 3.5.0-beta-9 which does not yet have the changes for deleting features of which the concurrent access check is a part.

**Comment by Rentier** [comment] 2018-11-28 10:47
Sorry for the duplicate.

**Closed by reckart** 2018-11-28 10:46 UTC
Labels: Module: Active Learning, 🐛Bug
