### ISSUE TITLE
Curation tab errors and cannot use

### ISSUE THREAD

**Issue by jeweinb** [inception-project/inception#4050] opened 2023-06-01 17:53 UTC
**Describe the bug**
When opening Curation tab of project I received the below error. What am I doing wrong?
![image](https://github.com/inception-project/inception/assets/87095331/892bca8d-84fa-4384-a3f4-81a7fe4534fc)

Version and build ID: inception-app-webapp-28.0-standalone.jar
OS: RHEL8
Browser: chrome
MariaDB: 10.5
nginx reverse proxy
openjdk version "11.0.19" 2023-04-18 LTS
OpenJDK Runtime Environment (Red_Hat-11.0.19.0.7-1.el8_7) (build 11.0.19+7-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.19.0.7-1.el8_7) (build 11.0.19+7-LTS, mixed mode, sharing)

**Comment by reckart** [comment] 2023-06-01 17:54
This is a known bug in INCEpTION 28.0. Please upgrade to INCEpTION 28.1.

**Comment by jeweinb** [comment] 2023-06-01 17:54
Welp thank you! I will do so immediately

**Comment by reckart** [comment] 2023-06-01 17:55
Duplicate of https://github.com/inception-project/inception/issues/4016

**Closed by reckart** 2023-06-01 17:55 UTC
Labels: 🐛Bug, Module: Curation
