### ISSUE TITLE
PDF editor annotation details

### ISSUE THREAD

**Issue by wpmp** [inception-project/inception#1083] opened 2019-03-30 12:31 UTC
**Is your feature request related to a problem? Please describe.**
Brat editor shows detailed information when hovering over annotations.
The PDF editor currently only shows some labels important for recommendations, e.g. to know which POS tag the recommendation is about.
Other information is missing

**Describe the solution you'd like**
PDF editor shows detailed information in a similar manner like brat editor does.

**Comment by reckart** [comment] 2022-09-02 22:45
Duplicate of https://github.com/inception-project/inception/issues/985

**Closed** 2022-09-02 22:45 UTC
Labels: 🎭 Duplicate, ⭐️ Enhancement, 🕶️ UX, Module: PDF editor
