### ISSUE TITLE
KB tooltip appears and dissappears constantly if size is too large

### ISSUE THREAD

**Issue by JavierLuna** [inception-project/inception#1502] opened 2019-11-04 15:42 UTC
**Describe the bug**
Sometimes (observed to happen when the tooltip is big) the KB tooltip will appear in such a way that the mouse is inside the tooltip. When that happens, the tooltip hides itself, but without tooltip and the mouse still hovering the annotation, the tooltip will appear again, looping forever.

This (sometimes) prevents clicking on the annotation.

**To Reproduce**
1. With KB tooltip enabled
2. Hover an annotation with a custom layer with a lot of features, so it generates a big tooltip.
3. _If we are lucky_, the tooltip will appear with the mouse inside it.
4. Looping happens!

**Expected behavior**
The tooltip appears in another place, so the mouse isn't inside it.

**Please complete the following information:**
 - Version and build ID: 0.11.2 cdd78cb18259c51647488fde393166646c7f30c7
 - OS: Ubuntu 18.04
 - Browser: Chrome, Firefox too

**Comment by reckart** [comment] 2019-11-04 16:26
Nasty. Do you actually need all the info in the tooltip? You can configure per feature whether it should be included in the tooltip or not.

**Comment by JavierLuna** [comment] 2019-11-04 16:35
Yes and no.
We are doing a kind of "revision" task, and having a tooltip with those features allows us to check annotations really quick.

This bug is aggravated by some annotators having really low-end screens (#1479).

We could even deactivate the tooltip but it is making this task much slower.

**Comment by reckart** [comment] 2019-11-06 10:04
The fix probably need to be implemented in the `adjustToCursor` method here:

https://github.com/webanno/webanno/blob/6b79ff6a65e503a9c5949df1b2d26460e39a40cf/webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer_ui.js#L268

**Comment by reckart** [comment] 2023-11-07 21:28
The old brat tooltip has been replaced with a new one - for the moment, I cannot reproduce the issue, so I am closing this now hoping it has been fixed.

See: https://github.com/inception-project/inception/issues/4139

**Closed by reckart** 2023-11-07 21:28 UTC
Labels: 🐛Bug, Requires upstream changes, Module: Annotation
