### ISSUE TITLE
Ability to see the status of background jobs in the UI

### ISSUE THREAD

**Issue by matchlesswei** [inception-project/inception#151] opened 2018-05-02 13:30 UTC
Create an API which can be used to display the status of background jobs of the current user / of all users, e.g. on the annotation page or elsewhere in the UI

- [x] status of the recommendation tasks
- [x] status of the indexing

**Comment by Rentier** [comment] 2019-01-09 10:01
Duplicate of #772

**Closed** 2023-07-29 19:45 UTC
Labels: ⭐️ Enhancement, Module: Scheduler
