### ISSUE TITLE
Import issues with 0.17.0

### ISSUE THREAD

**Issue by sabinebartsch** [inception-project/inception#1833] opened 2020-10-19 07:39 UTC
**Describe the bug**
INCEpTION 0.17.0 stand-alone fails to import projects.

**To Reproduce**
1. Exported projects (curated and non-curated) from other INCEpTION instance (versions 0.16.0 server and 0.16.1 stand-alone)
2. Import projects.
3. The Import dialog initially looks as if the import is happening (halo appears around the import button), but the project is not actually being imported. Tried this with several projects that import fine on 0.16.1 on the same machine (see Additional context below).
4. No error message, but no import happens.

**Expected behavior**
Expected projects to be imported and workable as in previous version.

**Please complete the following information:**
 - INCEpTION -- 0.17.0 (2020-10-07 11:44:43, build a4ce83232f58eba5968ccdf27c49c099c5e6a4ac)
 - OS: Windows 10 pro (64-bit)
 - Version 86.0.4240.75 (Official Build) (64-bit)

**Additional context**
Importing the same projects with 0.16.1 on the same machine and then actually working on them with 0.17.0 works fine and is my current work-around.

**Comment by reckart** [comment] 2020-10-19 07:53
@sabinebartsch Could it be a duplicate of #1828 ? Do you see the same error (flip() not found?)

**Comment by reckart** [comment] 2020-10-19 07:56
@sabinebartsch What Java version are you using?

**Comment by reckart** [comment] 2020-10-27 09:32
Duplicate of #1828 (fixed).

**Closed by reckart** 2020-10-27 09:32 UTC
Labels: 🐛Bug
