### ISSUE TITLE
Repeated results at search

### ISSUE THREAD

**Issue by Petitcriu** [inception-project/inception#3662] opened 2022-12-27 12:01 UTC
**Describe the bug**
When I search for existing annotations, I get results that keep repeating. I am searching for dependency relations, but the same problem already occurs at the token level when I search for simple word forms.

**To Reproduce**
1. Go to search
2. Write <Dependency.Relation="obl"/>

**Expected behavior**
The results with the label "obl" will be repeated at least once, possibly countless times.

**Screenshots**
This is a scrennshot of the results of a very small part of the project:
![grafik](https://user-images.githubusercontent.com/120732546/209663270-1cc41157-df00-4431-9d9e-bcda932414a3.png)

**Please complete the following information:**
 - Version and build ID: [see bottom of the browser screen] INCEpTION 23.7, build 8dec45b3
 - OS: [e.g. Windows, Linux, OS X]: Windows 10
 - Browser: [e.g. chrome, safari] Firefox

**Additional context**

**Comment by reckart** [comment] 2023-01-17 18:34
Duplicate of https://github.com/inception-project/inception/issues/3667.

**Closed by reckart** 2023-01-17 18:34 UTC
Labels: 🐛Bug, Module: Project Search, Needs confirmation
