### ISSUE TITLE
Annotation gets slower and slower, followed by Aw, Snap!'

### ISSUE THREAD

**Issue by david-waterworth** [inception-project/inception#2098] opened 2021-03-15 22:02 UTC
**Describe the bug**
I have around two hundred documents, each generally has ~10 sentences (although a couple are quite large ~1000 or more sentences which wasn't intentional). Over time annotation gets slower and slower, the delay after any action (ie selecting a recommendation or marking a span) gets longer and longer. Eventually, the page dies with a "Aw, Snap!'" message (after 30 minutes or so). Reloading the page clears the issue.

**To Reproduce**
It's difficult to provide much more than "annotation lots of documents", in general, it seems to occur when you already have a lot of annotated documents. When I started annotation I had approximately 200 unannotated documents, I observed the UI getting progressively slower but no crashes. Closing the tab and opening a new one resulted in performance improvement. Once I had about 100 documents annotated the crashes started and increased as I added more documents.

**Update**
- Issue has been observed when the recommender sidebar is open
- Issue has been observed when the active learning sidebar is open
- In other cases, the issue has so far not been observed

**Expected behavior**
Performance doesn't degrade over time, tabs don't crash.

**Screenshots**

**Please complete the following information:**
 - Version and build ID: 0.18.3 (2021-03-09 20:02:49, build bf16e970)
 - OS: Ubuntu 20.04
 - Browser: chrome

**Additional context**
Clicking too quickly to accept recommendations sometimes results in the recommendation being deleted or not accepted. I'm not sure if this is related but it gets a lot worse when the response time starts dropping (i.e. I suspect that clicking when the recommendations are being updated causes this issue and the slow UI exacerbates it).

**Comment by reckart** [comment] 2021-03-16 06:05
So the hypothesis here is that this is basically a thing of the browser, right? You work in Chrome on the annotation page - after a (long) while it starts getting slower. When you close the tab/window, speed comes back up again. I would assume things should also get faster again if you reload the page. During the process, you always stay on the annotation page and never switch to another page (at least not in that tab/window) - on that note, what does it mean to "... as I added more documents"?

It sounds a bit to me as if there might be some kind of memory leak or event handlers stacking up without being cleared properly.

So which features are you using on the annotation page: 
- basic annotation (with tagsets I would assume?)
- recommenders
- what else - any sidebars open?

What Chrome version are you using? In principle, it could also be a bug/leak in Chrome itself.

**Comment by reckart** [comment] 2021-03-16 06:21
Info on investigating memory leaks using the Chrome dev tools: https://developers.google.com/web/tools/chrome-devtools/memory-problems

**Comment by david-waterworth** [comment] 2021-03-16 06:41
Yes I'm pretty sure the problem isn't on the server side. I watched the logs and there's nothing of note in them. There's also not really much in the chrome logs either. Refreshing the tab doesn't seem to help, It seems I need to create a new one. I'll follow the guidance above and see if I can see anything problematic.

Chrome version is Version 88.0.4324.150 (Official Build) (64-bit)

I'm doing basic annotation, spans only without features (although the layer does have features as you cannot create a recommender on a custom layer without at least creating one although it's probably not strictly necessary). I have two span layers, one is strictly for metadata and is readonly but visible.

I have the recommender sidebar open.

That's about it really. Although I did notice (in a separate test project) that when I used an external recommender it posts the entire document collection to the train endpoint on pretty much every much ui action, way too often for the trainer to keep up. If this also happens with the internal ones then maybe that's a potential problem (the external recommender does have a lock so only one trainer will run at a time and the remainder return a failure status code). I understand the internal recommender is in (server) process.

**Comment by reckart** [comment] 2021-03-16 06:48
While a training action is still running, at most one additional equivalent training action (i.e. same project/user) is queued and whenever a new one comes it, it (should) replace the queue one. Actually, for training the same should happen when an external recommender is used. I would assume that what you see being sent to the external recommender in high frequency are prediction requests, not training requests.

Can you please try closing the recommender sidebar and annotating without it to see if that helps?

**Comment by david-waterworth** [comment] 2021-03-16 06:55
OK I'll try that.

I'm pretty sure they're training not prediction requests. The external server log is full of multiple messages indicating that there are several requests trying and failing to acquire the lock. Only the train endpoint has a lock on it. I'll recreate and post another issue on that later.

**Comment by jcklie** [comment] 2021-03-16 09:28
Right now, the external recommender sends all documents for training after an annotation. We are working on a newer API that does not have this problem. I try to add a fix that reduces this error also for the older version and get it into the next release. This is a server <-> server thing though, so should not be related to this issue.

**Comment by david-waterworth** [comment] 2021-03-17 06:15
It does seem possible that having the sidebar open is contributing to the issue? I didn't have any issues today with it closed. I wasn't doing as much annotation though.

**Comment by reckart** [comment] 2021-03-17 06:22
I suspect that the updating of the chart in the sidebar might be done in a way that doesn't properly free resources. We have that on chart on the list of things to refactor anyway. However, I think we'll leave this refactoring for one of the next versions (i.e. not for 0.19.0, maybe 0.19.1).

**Comment by reckart** [comment] 2021-03-23 14:29
@david-waterworth May I assume that we can take it as proven that the recommender sidebar is causing the problem? Or do you continue running into the issue with the sidebar closed?

**Comment by david-waterworth** [comment] 2021-03-24 04:26
@reckart yes I'm fairly confident that the issue only occurs when the sidebar is open.

**Comment by Maroussia** [comment] 2021-03-28 10:17
Hi, I am not sure this is the right place to report, please apologise if I am mistaking, but I am wondering whether my issue is similar to the one described by @david-waterworth or if I should open a new thread. I am also getting this 'Aw, Snap' interruption and I have kept the sidebar closed, as I noticed that it was slowing down the annotation considerably, which is anyway already quite slow. Is there anything I should try apart from what @reckart suggested here?

I am using Inception Version 0.19 on Brave (Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)) on Ubuntu 20.04.

So far, I could annotate (slowly and with interruptions) one text of 300 lines (5963 tokens) with chunks and NER using as recommenders String Matcher and Multi-Token NLP, and I am currently trying to annotate another text of 500 lines (14339 tokens), only chunks as it is getting too slow and buggy otherwise. Both texts are in classical Arabic. Could the length of the text be the problem? Is there an ideal length for a document?

**Comment by reckart** [comment] 2021-03-28 10:22
Does the problem temporarily go away after restarting the browser? How many lines did you configure to show at a time in the preferences dialog on the annotation page?

If you can consistently reproduce the problem, would it be possible to provide us with a project export so we can also reproduce the issue and investigate?

**Comment by Maroussia** [comment] 2021-03-28 10:46
Restarting the browser does not change anything (today, after restarting the browser, I got the 'Aw, Snap' message each time I tried to load the document). The only 'solution' I found is restarting Inception all together.

I am not sure how consistent my problems are. The annotation process is consistently slow (with and without recommenders) for sure. The 'Aw, Snap' interruption is less consistent but it seems recurrent. In any case, I am happy to provide you with a project export, where shall I send it?

Many thanks @reckart for your assistance!

**Comment by reckart** [comment] 2021-03-28 10:54
Let's open a new issue for this. I believe it is a different problem from what David experienced. Can you see my mail address in the git commits?

**Comment by reckart** [comment] 2021-03-28 10:54
Let's open a new issue for this. I believe it is a different problem from what David experienced. Can you see my mail address in the git commits?

**Comment by Maroussia** [comment] 2021-03-28 11:18
Yes, just sent you the link to the project export and let me know what you think I should call this issue :)

**Comment by reckart** [comment] 2021-03-28 11:23
Got the Mail. I will get back to you later when I had the chance to download and look at it. Give the issue whatever title you like. If necessary or can be renamed later.

**Comment by david-waterworth** [comment] 2021-04-15 05:42
@reckart - this happened again today, but this time using the Active Learning module with the sidebar open (previously it was the recomender sidebar). I've not seen it other than with the sidebar open.

**Comment by reckart** [comment] 2021-04-18 09:44
Ok, thanks. We'll need to do some browser-based memory profiling to track that down. At the moment, it seems to me that the issue is somewhat inconvenient but not a blocker and doesn't seem to affect too many people.

Anybody: if you experience this issue as well, let us know.

**Comment by reckart** [comment] 2021-05-02 20:02
Memory analysis in Chrome indicates that when the recommender sidebar is open, a large number of detached SVG elements  are accumulating in memory and they trace back to the C3 chart.

**Comment by reckart** [comment] 2021-05-02 20:33
The best fix is to re-write the chart from scratch - or to solve the issue of providing a historized view on the evaluation results differently, e.g. by showing fire-lines per recommender. Anyway, for the time being, I'll remove the chart.

**Comment by reckart** [comment] 2021-05-03 21:01
It appear that the Bootstrap Select component might have a leak and redrawing it often (e.g. on every selection) causes memory usage to accumulate. We have one of the on the active learning sidebar and also one in the layer selector of the annotation detail panel. I'm looking into excluding them from rendering unless absolutely necessary.

**Comment by reckart** [comment] 2021-05-04 06:47
So, I have changed the most obvious things that came up in the analysis. In general, it seems that there might still be some leaking but at least for me it isn't obvious to see where it comes from in the Chrome analyzer - and it is much less now, so I hope it won't be an issue unless somebody annotates for really a long time without leaving the annotation page.

**Closed by reckart** 2021-05-04 06:48 UTC
Labels: Module: Recommender, browser-chrome, 🐛Bug
