### ISSUE TITLE
Suggestion list in concept feature editor appears empty

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#72] opened 2018-04-20 13:14 UTC
The suggestion list in the concept feature editor may now appear empty although it actually has content. May be related to the changes made for #27 - the UI label of the concept is simply returned as an empty string.

Try with the Wine ontology.

**Comment by betoboullosa** [comment] 2018-04-27 12:38
Unable to reproduce it. Closing.

**Closed** 2018-04-27 12:38 UTC
Labels: Module: Entity Linking, 🐛Bug, 🚫Invalid
