### ISSUE TITLE
404 - Not found  when opening a document in the default editor

### ISSUE THREAD

**Issue by RubberDog** [inception-project/inception#2959] opened 2022-04-08 09:40 UTC
**Describe the bug**
After updating to INCEpTION 23.0.1 I receive the following message when opening a document in the default editor:

Whoops!
Something went wrong...

Status:  404 Not Found
Servlet: dispatcherServlet
Request path: /inception/resources/pdfanno/index.html
Message:    
Application Version: 23.0.1 (2022-04-02 23:20:47, build edf60f9c)
Java Version: Ubuntu 11.0.14.1
Operating System: Linux 5.4.0-107-generic amd64 

**To Reproduce**
1. Open a project
2. Select a .pdf for annotation
3. See error

**Expected behavior**
Open the requested file (pdf) in the editor

**Screenshots**

![image](https://user-images.githubusercontent.com/9200073/162408873-81d1dc59-5f2e-488c-a6a2-06176fd4a983.png)

**Please complete the following information:**
 - Version and build ID: 23.0.1 (2022-04-02 23:20:47, build edf60f9c) 
 - OS: Ubuntu Server 20.04.4
 - Browser: Chrome, Firefox

**Additional context**
I have this very same error in a freshly set up Ubuntu VM following the 23.0.1 admin guide, using the standalone .jar and on a live server running Inception as docker container and the standalone .jar for testing this issue.
The server and VM are running nginx as a reverse proxy.

**Comment by reckart** [comment] 2022-04-08 09:47
Duplicate of https://github.com/inception-project/inception/issues/2946 which is already fixed. Will be included in v23.1 to be released soon.

**Closed** 2022-04-08 09:48 UTC
Labels: 🐛Bug, Module: PDF editor
