### ISSUE TITLE
document doesn't jump to the next suggestion location if "auto-scroll" is enabled

### ISSUE THREAD

**Issue by matchlesswei** [inception-project/inception#61] opened 2018-04-18 17:48 UTC
If "auto-scroll" is enabled and active learning session is open, the document doesn't jump to the next suggestion location after acceptance in the main editor.

Check where auto-scroll is called.
Try different orders. (move refresh documents)

**Comment by matchlesswei** [comment] 2018-06-07 09:01
I cannot reproduce this bug anymore.

**Comment by reckart** [comment] 2018-06-08 08:47
Closing as "cannot reproduce" then. If anybody notices it again, please re-open (or create new issue).

**Closed by reckart** 2018-06-08 08:47 UTC
Labels: Cannot Reproduce, Module: Active Learning, 🐛Bug
