### ISSUE TITLE
Customizable UI name for tagsets 

### ISSUE THREAD

**Issue by qiuwei** [inception-project/inception#891] opened 2019-01-22 03:49 UTC
**Is your feature request related to a problem? Please describe.**
As we can already customize the UI name differently for the attributes,  it's appealing to have this feature for tagsets as well.  

**Describe the solution you'd like**
make the UI name for tagsets customizable.

**Comment by reckart** [comment] 2019-01-22 06:46
I wonder... would the following be an alternative?

You could set up a "flat" Knowledge base and use a concept feature instead of a string feature. For items in the KB, you can define custom labels - however, the string that would be written to the actual annotation would be an IRI (and if you create the KB inside INCEpTION instead of importing it, it would be a randomized IRI).

**Comment by reckart** [comment] 2019-08-28 07:26
Seems to be a duplicate of #1250 and #1250 seems to have the better description.

**Closed** 2019-08-28 07:26 UTC
Labels: 🎭Duplicate
