### ISSUE TITLE
Export of single document fails when username is too short

### ISSUE THREAD

**Issue by perronld** [inception-project/inception#3630] opened 2022-12-13 02:39 UTC
### Describe the bug

We unfortunately have a username with only two characters in our installation.

When we try to export a project using Webanno, we hit this exception (actual username is replaced by AA):
```
Caused by: java.lang.IllegalArgumentException: Prefix string "AA" too short: length must be at least 3
        at java.io.File.createTempFile(File.java:2104) ~[?:?]
        at java.io.File.createTempFile(File.java:2175) ~[?:?]
        at de.tudarmstadt.ukp.clarin.webanno.api.format.FormatSupport.write(FormatSupport.java:181) ~[inception-api-formats-25.4.jar!/:?]
```

https://github.com/inception-project/inception/blob/e3883d636857416e2846b9980403adc1ab3f8ba5/inception/inception-api-formats/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/format/FormatSupport.java#L200

An easy fix would be to restrict usernames to have a minimum of three characters. Unfortunately, for our existing installation, it's seems impossible to rename a username without breaking everything, since files and folders in the repository are named against the username. :(

### To Reproduce

1. Create a user with a username of length 1 or 2
2. Have him work on a project
3. Try to export the project with Webanno format

### Environment

Version and build ID:  INCEpTION -- 25.4 (2022-11-08 12:45:47, build 1aeb414a)
Operating system: Linux Ubuntu 20.04

**Comment by reckart** [comment] 2022-12-13 07:33
You can change the minimum username length by adding a configuration property to your `settings.properties` file:

```
security.minimum-username-length=2
```

See: https://inception-project.github.io/releases/26.1/docs/admin-guide.html#sect_security_polixy

**Comment by reckart** [comment] 2022-12-13 07:35
Oh, I see - this seems to be a restriction on the creation of temporary files!

**Comment by reckart** [comment] 2022-12-13 07:38
I believe this issue should already been fixed in newer releases. Can you please try INCEpTION 26.1?

**Comment by reckart** [comment] 2022-12-13 08:25
Ok, I can reproduce it in 26.1 - investigating.

**Closed** 2022-12-13 11:31 UTC
Labels: 🐛Bug

**Comment by perronld** [comment] 2022-12-13 13:36
Thanks a lot! That was quick!

**Comment by perronld** [comment] 2022-12-13 13:40
No worries, I can temporarily use the snapshot build to perform the export, then rollback our VM.
