### ISSUE TITLE
Change the type of the layer

### ISSUE THREAD

**Issue by 2xXLunAXx2** [inception-project/inception#3657] opened 2022-12-25 07:56 UTC
**Describe the bug**
If I accidently chose the wrong type of layer (in my case, I chose a chain instead of a span) and I noticed it after I already started tagging, I cannot change the type of the layer. I need to recreate the layer and lose the tags I already tagged. 

**To Reproduce**
1. Create a new layer (choose any type, it doesn't matter). 
2. Save the layer. 
3. Now the type of the layer cannot be changed.

**Expected behavior**
The type of the layer can be changed. Alternatively, the tags of a layer can move to another (new) layer with the right type of layer. 

**Please complete the following information:**
 - Version and build ID: 25.1
 - OS: Windows
 - Browser: chrome

Thank you!

**Comment by yanirmr** [comment] 2022-12-29 08:54
Hi @reckart ,

We're not sure if the issue described by @2xXLunAXx2  is a bug or just a proposed feature, but either way, we want to figure out how to move forward. We've stopped all tagging progress for now as we see that we have three options, each of which carries its own set of potential problems:

1. Continue tagging with the chain-type method, but the risk is that all of the tags we've created so far and any future tags will be lost and we'll have to start the tagging process over again.
2. Create a new layer for the tags (span-type), but the risk is that we won't be able to connect the historic tags (chain-type) with the new ones (span-type).
3. The third and worst-case scenario is deleting the entire tagging history and starting over.

What do you think we should do in this situation?

Thank you very much for your help.

**Comment by reckart** [comment] 2022-12-29 11:05
Tricky. You cannot change the type of a layer - that is not a bug, it is a fact. Doing so would be pretty complicated. E.g. what would it mean to change a relation to a span? Let's not go there.

There are a number of ways this can be done.

The probably "best supported" way would be this:

* create a new span layer which will be the target layer
* enable the remote API
* write a python script using DKPro Cassis that downloads each annotation document in turn, copies the data from the old chain layer to annotations in the new target layer and then uploads these annotations again
* once you have checked that everything worked fine, delete the old layer

Other ways may include e.g.

* exporting the data in TSV format and manually modifying the file header, then reimporting
* going directly to the database and changing the layer type of the chain layer - but then also changing the name of the layer from "...XXX" to "...XXXLink"

Whatever you do, I would strongly recommend you make a backup (e.g. an export of your project) before doing it and you check that the backup can be restored properly.

**Comment by reckart** [comment] 2023-01-04 22:05
I'll close this one. Feel free to add more comments and if necessary, we can re-open the issue.

**Closed by reckart** 2023-01-04 22:05 UTC
Labels: Support request
