### ISSUE TITLE
posting user annotations via Aero API raises exception in Swagger 

### ISSUE THREAD

**Issue by mromanello** [inception-project/inception#934] opened 2019-02-06 16:45 UTC
**Describe the bug**

Posting user annotations to INCEpTION via its Aero API does not work properly in Swagger, but it does work when using e.g. `cURL`.

**To Reproduce**
1. Go to `<inception/>swagger-ui.html`
2. Expand section `POST /api/aero/v1/projects/{projectId}/documents/{documentId}/annotations/{userId}`
3. Fill in parameters (I have: `projectId = 3`, `documentId = 384`, `userId = mromanello`, `aFile` (I've selected via the browser an `.xmi` file), `format = xmi`, `state = NEW`

```json
{
  "messages": [
    {
      "level": "ERROR",
      "message": "Internal server error: Required request part 'content' is not present"
    }
  ]
}
```

**Expected behavior**

If I use `curl` instead the following command works just fine:

```bash
curl -u mromanello:<pwd> -X POST --header 'Content-Type: multipart/form-data' --header 'Accept: application/json' -F format=xmi -F state=NEW -Fcontent=@GDL-1798-08-30-a-i0013.xmi  'http://<inception_url>/api/aero/v1/projects/3/documents/384/annotations/mromanello'
```

**Please complete the following information:**
 - Version and build ID: [see bottom of the browser screen]
 - OS: Mac OS 10.11.6
 - Browser: chrome

**Comment by UWinch** [comment] 2019-05-16 11:25
Are you still experiencing this issue? I'm having trouble reproducing it on my machine.

**Comment by UWinch** [comment] 2019-07-18 08:00
I'm closing this issue because I couldn't reproduce the problem. Please open it again if the problem persists.

**Closed by UWinch** 2019-07-18 08:00 UTC
Labels: 🐛Bug
