### ISSUE TITLE
Double polarities with constraints

### ISSUE THREAD

**Issue by s2fische** [inception-project/inception#4948] opened 2024-07-18 15:23 UTC
For a specific kind of span annotation ("Codierungen", in purple), INCEpTION still allows for double (or more) polarities to be selected after changing the type even though constraints are used.

To reproduce: set a "Codierung" span, select 1_Art and a corresponding 2_Polarität, then change 1_Art to a different type and select a new corresponding 2_Polarität for this kind. The problem is that the first choice for 2_Polarität stays selected in addition to the new one, when only one should be allowed, see screenshots:

Here, the annotator first selected 1_Art "Harmonisch-disharmonisch" and then changed to "Tief-oberflächlich"; however, the 2_Polariät "disharmonisch/fragmentiert" stayed selected:
![Codierungen](https://github.com/user-attachments/assets/34036b1b-8ae6-4e1b-a442-354c0adedfc8)

Here, the annotator first selected 1_Art "Harmonisch-disharmonisch" and then changed to "Gesund-krank"; however, the 2_Polariät "harmonisch/ganzheitlich" stayed selected:
<img width="923" alt="Screenshot 2024-07-10 113322" src="https://github.com/user-attachments/assets/62b60410-f8eb-49c3-9b03-e7d19da875c5">

**Please complete the following information:**
 - Version and build ID: INCEpTION 33.1 (2024-06-25 09:45:14, build 26410d34)
 - OS: Windows 11
 - Browser: Chrome

**Comment by reckart** [comment] 2024-07-19 20:15
Duplicate of https://github.com/inception-project/inception/issues/4942

**Closed by reckart** 2024-07-19 20:15 UTC
Labels: 🐛Bug, Module: Annotation
