### ISSUE TITLE
Hide arcs in PDF editor by default until annotation is selected

### ISSUE THREAD

**Issue by tpluscode** [inception-project/inception#4582] opened 2024-03-03 16:01 UTC
**Is your feature request related to a problem? Please describe.**

Given many links, the editor view can quickly become very cluttered with arrows obscuring content. It then becomes quite difficult to select spans to annotate

**Describe the solution you'd like**

It would be nice to be able to hide link arcs by default, either as a global setting, or specific switch in property settings.

Such hidden arcs would then only appear once an annotation is selected which is the source or target of a link

**Comment by tpluscode** [comment] 2024-03-03 21:23
I suppose similar could apply to relations...

**Comment by reckart** [comment] 2024-03-03 21:30
It's probably not something I will get around to doing soon... 

Didn't you mention you like coding JavaScript? The PDF editor is JavaScript ;)

**Comment by reckart** [comment] 2024-06-03 20:28
Duplicate of #4826

@tpluscode not the default, but it is an option now.

**Closed by reckart** 2024-06-03 20:28 UTC
Labels: ⭐️ Enhancement, Module: PDF editor
