### ISSUE TITLE
Auto Complete field doesn't show suggestion for concept linking

### ISSUE THREAD

**Issue by naveen2507** [inception-project/inception#650] opened 2018-11-13 13:49 UTC
**Describe the bug**
Auto Complete field doesn't show suggestion for concept linking for Named Entity identifier when the KB supports concept linking

**To Reproduce**
1. Go to a project with a document and KB
2. Click on Annotations and try to do some NE annotation
3. Auto complete field doesn't show a dropdown

**Expected behavior**
It should show ideally. 

**Please complete the following information:**
 - Version and build ID: [Technische Universität Darmstadt -- Computer Science Department -- INCEpTION 𝜶 -- 0.7.0-SNAPSHOT (2018-11-13 14:09:34, build 08971fb36276db902047d402486064d9d41bb0ee)]
 - OS: [Linux]
 - Browser: [chrome]

**Comment by naveen2507** [comment] 2018-11-13 14:29
Issue will be covered in #619. But needs to be checked.

**Comment by reckart** [comment] 2018-11-13 15:11
@naveen2507 For me, the dropdown appears, but it takes a very long time.

INCEpTION 𝜶 -- 0.7.0-SNAPSHOT (2018-11-12 18:35:27, build c18818e13b3872ea3ba2915b96d308a10be0246e)

**Comment by naveen2507** [comment] 2018-11-13 15:14
@reckart for me it doesn't work at all. (in cases where KB supports concept linking)

**Comment by reckart** [comment] 2018-11-13 15:37
I'm using this KB configuration:

![2018-11-13_16-37-01](https://user-images.githubusercontent.com/1410238/48424202-6ad5ae00-e762-11e8-9d76-a8875fd10f7e.png)

**Comment by reckart** [comment] 2018-11-16 12:00
@naveen2507 Try force-re-indexing the KB on the KB settings page in the project settings - then see again whether it works.

**Comment by reckart** [comment] 2018-11-20 21:15
I think that I have found at least one reason why this could happen: when importing a project where the `maxResults` setting did not exist yet, then `maxResults` is set to `0` meaning that all queries are limited to return zero results. Working on a fix...

**Comment by reckart** [comment] 2018-11-21 19:13
Ok, so this works for Virtuoso - it doesn't work for the Wine Ontology in a local KB. The reason for this is #560 (we have already a PR for a fix, but the fix is not good yet: #602).

So this is a duplicate of #560 and I am closing it as such.

**Closed by reckart** 2018-11-21 19:13 UTC
Labels: Module: Entity Linking, 🎭Duplicate, 🐛Bug
