### ISSUE TITLE
some Strange recommendations of String Matcher after Pre-loading with Gazetters 

### ISSUE THREAD

**Issue by JackDapid** [inception-project/inception#1520] opened 2019-11-19 09:05 UTC
**Describe the bug**
If some Gazetter files are used with the String Matcher recommender some recommendations are very strange, e.g. it looks like some Gazetter entries are not taken into account? Or some space separated annontations seem to be split up or wrongly positioned?
- Does each Project have it's own String Matcher? (maybe some strange effects from other project)
- is the String Matcher retrained from scratch if new gazetter files added? 

**To Reproduce**
1. Create a new Project
2. Upload a new document
3. Create a new String Matcher recommender and upload a long (some hundred lines) Gazetter file

**Expected behavior**
understandable annotation recommendations

**Screenshots**
![image](https://user-images.githubusercontent.com/8346230/69130355-ae1ed700-0ab0-11ea-8f54-ce8e0b37453c.png)
Gazetter file:
> [...]
> Niger	LOC:country
> Nigeria	LOC:CITY
> [...]

OR

![image](https://user-images.githubusercontent.com/8346230/69131296-6dc05880-0ab2-11ea-887b-fed9ef84399e.png)
> Switzerland	LOC:country
> Syria	LOC:country
> Syrian Arab Republic	LOC:country
> Taiwan	LOC:country

OR

![image](https://user-images.githubusercontent.com/8346230/69132986-677fab80-0ab5-11ea-871c-db862c8bb07d.png)
Using only 1 gazetter file with:
> Trinidad and Tobago	LOC:country

AND
![image](https://user-images.githubusercontent.com/8346230/69133016-76665e00-0ab5-11ea-9b3a-f847a2158c00.png)
Using 2 gazetter files with:
> Trinidad and Tobago	LOC:country
>Trinidad	LOC:city

**Please complete the following information:**
 - Version and build ID: 0.13.0
 - OS: OSX
 - Browser: chrome

**Additional context**

**Comment by reckart** [comment] 2019-11-19 09:20
The matcher is per user/per project. So there should neither be cross-user nor cross-project effects.

The matcher should be retrained if a new file is added. You can also manually trigger a reinitialization via the "Retrain" button in the "Recommender" sidebar on the annotation page.

Looks like we might have some kind of off-by-one bug here. Could you provide the test files you were using so we can reproduce it?

**Comment by JackDapid** [comment] 2020-01-22 12:48
I can't currently reproduce with 0.14.2 ... will keep and eye on it, so ok to leave it on Stale and I will reply back after some further tests

**Comment by reckart** [comment] 2020-07-21 10:04
Closing as there was no more feedback.

**Closed by reckart** 2020-07-21 10:04 UTC
Labels: Module: Recommender, 🐛Bug, 🚫Invalid
