### ISSUE TITLE
Searching for words does not work. Instead we get the message: "Index still building. Try again later."

### ISSUE THREAD

**Issue by kapllan** [inception-project/inception#4850] opened 2024-06-05 10:41 UTC
**Describe the bug**
A few days ago, we started to experience some issues with the search panel on the left side. Whenever we are trying to search for a word in a document (or the entire documents), we get the message "Index still building. Try again later." (see screenshot below). We find this strange because we have never experienced this issue before and building an index should not take days. Our hardware seems sufficient to handle the data load, so we do not believe a lack of RAM etc. could be the reason.

**Screenshots**
![Xnip2024-06-05_12-38-23](https://github.com/inception-project/inception/assets/50752938/5ec5b6d8-9c7e-4b60-9e3b-7662277f10c5)

**Please complete the following information:**
 -  INCEpTION -- 32.2 (2024-05-14 20:46:45, build 101ef653) 
 - OS:  Linux
 - Browser: Firefox

**Additional context**
Currently, we are running INCEpTION on a server making it accessible via a URL for multiple users.

**Comment by reckart** [comment] 2024-06-05 18:47
You probably ran into this issue: https://github.com/inception-project/inception/issues/4827 (which is fixed already for the next major release).

Please try manually triggering a re-index and then checking if an error is generated in the log.

**Comment by reckart** [comment] 2024-06-05 18:48
And you may have to restart INCEpTION before you are able to properly trigger a re-indexing.

**Comment by kapllan** [comment] 2024-06-06 06:40
Thanks for the prompt response. So, I can do that like this "java -jar inception-app-webapp-24.0-standalone.jar search reindex" as described here: https://inception-project.github.io/releases/32.3/docs/admin-guide.html#_full_text_indices ?

**Comment by reckart** [comment] 2024-06-06 06:54
That command reindexes all projects and is useful e.g. when the search backend has had an incompatible change from one version to another. 

In your case, you probably only want to reindex a single project which can be done from the **Annotation** panel in the **Project settings** of your project.

**Comment by reckart** [comment] 2024-06-10 17:45
Closing as duplicate of #4827.

**Closed by reckart** 2024-06-10 17:45 UTC
Labels: 🐛Bug, Module: Project Search
