### ISSUE TITLE
Cannot invoke "java.util.Map.get(Object)" because "this.val$aColors" is null

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2601] opened 2021-09-16 16:20 UTC
**Describe the bug**

Cannot invoke "java.util.Map.get(Object)" because "this.val$aColors" is null

**To Reproduce**
Kibana

**Please complete the following information:**
 - Version and build ID: 20.4

**Additional context**

```
Sep 16 17:19:19 blinky inception-stable.jar[7854]: 2021-09-16 17:19:19 ERROR [habernal] AjaxComponentRespondListener - Unable to trigger respond listener callback
Sep 16 17:19:19 blinky inception-stable.jar[7854]: java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "this.val$aColors" is null
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at de.tudarmstadt.ukp.clarin.webanno.ui.curation.component.AnnotatorsPanel$2.getColor(AnnotatorsPanel.java:630) ~[inception-ui-curation-20.4.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at de.tudarmstadt.ukp.clarin.webanno.brat.render.BratRenderer.render(BratRenderer.java:184) ~[inception-brat-editor-20.4.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at de.tudarmstadt.ukp.clarin.webanno.ui.curation.component.AnnotatorsPanel.render(AnnotatorsPanel.java:435) ~[inception-ui-curation-20.4.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at de.tudarmstadt.ukp.clarin.webanno.ui.curation.component.AnnotatorsPanel.lambda$updatePanel$0(AnnotatorsPanel.java:606) ~[inception-ui-curation-20.4.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.wicket.util.visit.Visits.visitChildren(Visits.java:144) ~[wicket-util-9.3.0.jar!/:9.3.0]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.wicket.util.visit.Visits.visitChildren(Visits.java:162) ~[wicket-util-9.3.0.jar!/:9.3.0]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.wicket.util.visit.Visits.visitChildren(Visits.java:123) ~[wicket-util-9.3.0.jar!/:9.3.0]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.wicket.MarkupContainer.visitChildren(MarkupContainer.java:967) ~[wicket-core-9.3.0.jar!/:9.3.0]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at de.tudarmstadt.ukp.clarin.webanno.ui.curation.component.AnnotatorsPanel.updatePanel(AnnotatorsPanel.java:588) ~[inception-ui-curation-20.4.jar!/:?]Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at de.tudarmstadt.ukp.clarin.webanno.ui.curation.component.AnnotatorsPanel.lambda$requestRender$d2bf43c0$1(AnnotatorsPanel.java:753) ~[inception-ui-curation-20.4.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at de.tudarmstadt.ukp.clarin.webanno.support.wicket.AjaxComponentRespondListener.onTargetRespond(AjaxComponentRespondListener.java:64) [inception-support-20.4.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.wicket.ajax.AjaxRequestHandler.respond(AjaxRequestHandler.java:267) [wicket-core-9.3.0.jar!/:9.3.0]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:910) [wicket-core-9.3.0.jar!/:9.3.0]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:63) [wicket-request-9.3.0.jar!/:9.3.0]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:294) [wicket-core-9.3.0.jar!/:9.3.0]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:255) [wicket-core-9.3.0.jar!/:9.3.0]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:277) [wicket-core-9.3.0.jar!/:9.3.0]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.wicket.protocol.ws.AbstractUpgradeFilter.processRequestCycle(AbstractUpgradeFilter.java:67) [wicket-native-websocket-core-9.3.0.jar!/:9.3.0]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:208) [wicket-core-9.3.0.jar!/:9.3.0]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:307) [wicket-core-9.3.0.jar!/:9.3.0]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:186) [spring-orm-5.3.8.jar!/:5.3.8]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.7.jar!/:5.4.7]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) [spring-security-web-5.4.7.jar!/:5.4.7]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) [spring-security-web-5.4.7.jar!/:5.4.7]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) [spring-web-5.3.8.jar!/:5.3.8]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) [spring-web-5.3.8.jar!/:5.3.8]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.3.8.jar!/:5.3.8]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.8.jar!/:5.3.8]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.3.8.jar!/:5.3.8]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.8.jar!/:5.3.8]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.3.8.jar!/:5.3.8]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.8.jar!/:5.3.8]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:433) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) [tomcat-embed-core-9.0.45.jar!/:?]
Sep 16 17:19:19 blinky inception-stable.jar[7854]:         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.45.jar!/:?]
```

**Comment by reckart** [comment] 2021-09-25 09:17
I have no idea in which situation this problem could occur, but I hope that https://github.com/inception-project/inception/pull/2622 either fixes it or at least constraints its effect so we can better point if it continues to happen.

**Comment by reckart** [comment] 2021-09-30 19:24
Duplicate of #2635

**Closed by reckart** 2021-09-30 19:24 UTC
Labels: 🐛Bug, Module: Curation
