### ISSUE TITLE
File failed to upload: Processing of multipart/form-data request failed

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2355] opened 2021-06-09 20:25 UTC
**Describe the bug**
File failed to upload: Processing of multipart/form-data request failed

**To Reproduce**

tbd (Kibana)

**Expected behavior**

No error

**Screenshots**

**Please complete the following information:**
 - Version and build ID: 0.19.6

**Additional context**

```
Jun 09 12:31:06 blinky inception-stable.jar[12116]: org.apache.commons.fileupload.FileUploadBase$IOFileUploadException: Processing of multipart/form-data request failed. java.io.EOFException
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:350) ~[commons-fileupload-1.4.jar!/:1.4]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.wicket.protocol.http.servlet.MultipartServletWebRequestImpl.parseFileParts(MultipartServletWebRequestImpl.java:196) ~[wicket-core-9.2.0.jar!/:9.2.0]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.wicket.markup.html.form.Form.handleMultiPart(Form.java:1464) [wicket-core-9.2.0.jar!/:9.2.0]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:793) [wicket-core-9.2.0.jar!/:9.2.0]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior.onEvent(AjaxFormSubmitBehavior.java:176) [wicket-core-9.2.0.jar!/:9.2.0]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:146) [wicket-core-9.2.0.jar!/:9.2.0]

...

Jun 09 12:31:06 blinky inception-stable.jar[12116]: Caused by: org.apache.catalina.connector.ClientAbortException: java.io.EOFException
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:340) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.catalina.connector.InputBuffer.checkByteBufferEof(InputBuffer.java:632) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:362) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:132) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at java.io.FilterInputStream.read(FilterInputStream.java:132) ~[?:?]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.commons.fileupload.util.LimitedInputStream.read(LimitedInputStream.java:132) ~[commons-fileupload-1.4.jar!/:1.4]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.commons.fileupload.MultipartStream$ItemInputStream.makeAvailable(MultipartStream.java:1027) ~[commons-fileupload-1.4.jar!/:1.4]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.commons.fileupload.MultipartStream$ItemInputStream.read(MultipartStream.java:931) ~[commons-fileupload-1.4.jar!/:1.4]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at java.io.InputStream.read(InputStream.java:218) ~[?:?]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.commons.fileupload.util.Streams.copy(Streams.java:98) ~[commons-fileupload-1.4.jar!/:1.4]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.commons.fileupload.util.Streams.copy(Streams.java:68) ~[commons-fileupload-1.4.jar!/:1.4]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:346) ~[commons-fileupload-1.4.jar!/:1.4]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         ... 96 more
Jun 09 12:31:06 blinky inception-stable.jar[12116]: Caused by: java.io.EOFException
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.coyote.ajp.AjpProcessor.read(AjpProcessor.java:1237) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.coyote.ajp.AjpProcessor.readMessage(AjpProcessor.java:570) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.coyote.ajp.AjpProcessor.receive(AjpProcessor.java:532) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.coyote.ajp.AjpProcessor.refillReadBuffer(AjpProcessor.java:639) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.coyote.ajp.AjpProcessor$SocketInputBuffer.doRead(AjpProcessor.java:1296) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.coyote.Request.doRead(Request.java:555) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:336) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.catalina.connector.InputBuffer.checkByteBufferEof(InputBuffer.java:632) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:362) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:132) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at java.io.FilterInputStream.read(FilterInputStream.java:132) ~[?:?]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.commons.fileupload.util.LimitedInputStream.read(LimitedInputStream.java:132) ~[commons-fileupload-1.4.jar!/:1.4]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.commons.fileupload.MultipartStream$ItemInputStream.makeAvailable(MultipartStream.java:1027) ~[commons-fileupload-1.4.jar!/:1.4]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.commons.fileupload.MultipartStream$ItemInputStream.read(MultipartStream.java:931) ~[commons-fileupload-1.4.jar!/:1.4]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at java.io.InputStream.read(InputStream.java:218) ~[?:?]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.commons.fileupload.util.Streams.copy(Streams.java:98) ~[commons-fileupload-1.4.jar!/:1.4]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.commons.fileupload.util.Streams.copy(Streams.java:68) ~[commons-fileupload-1.4.jar!/:1.4]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:346) ~[commons-fileupload-1.4.jar!/:1.4]
Jun 09 12:31:06 blinky inception-stable.jar[12116]:         ... 96 more
```

Before that, there is also

```
Jun 09 12:31:15 blinky inception-stable.jar[12116]: 2021-06-09 12:31:15 ERROR [redacted] CurationPage - Error: This document has the state CURATION_INPROGRESS but there are no finished annotation documents! This can for example happen when curation on a document has already started and afterwards all annotators have been remove from the project, have been disabled or if all were put back into INPROGRESS mode. It can also happen after importing a project when the users and/or permissions were not imported (only admins can do this via the projects page in the) administration dashboard and if none of the imported users have been enabled via the users management page after the import (also something that only administrators can do).
Jun 09 12:31:15 blinky inception-stable.jar[12116]: java.lang.IllegalStateException: This document has the state CURATION_INPROGRESS but there are no finished annotation documents! This can for example happen
when curation on a document has already started and afterwards all annotators have been remove from the project, have been disabled or if all were put back into INPROGRESS mode. It can also happen after importing a project when the users and/or permissions were not imported (only admins can do this via the projects page in the) administration dashboard and if none of the imported users have been enabled via the users management page after the import (also something that only administrators can do).
```

**Comment by reckart** [comment] 2021-06-11 20:32
Sounds a bit like somebody was uploading a (large?) file and then aborted, maybe by closing the browser window.

**Comment by reckart** [comment] 2021-12-07 08:47
Has not appeared since and have also not been able to reproduce. Workload management has since changed. Closing for now. If it reappears, please re-open or open again as a new issue with instructions on how to reproduce.

**Closed by reckart** 2021-12-07 08:47 UTC
Labels: 🐛Bug, 🚫Invalid
