### ISSUE TITLE
RC5 "Whoops" when document locked and cannot curate or unlock

### ISSUE THREAD

**Issue by david-waterworth** [inception-project/inception#2483] opened 2021-07-15 06:24 UTC
I'm using v 0.20-rc-5, I locked my document and the message below was written in the service log, and the UI showed the Whoops page. I can still open the document and it's locked, but I cannot curate it? When I select curation, the open document dialogue is empty (should contain 1 document?). I'm using the admin user which has the curation role.  When I go to monitoring it lists the document with "Curation" unchecked and admin checked.

So I'm stuck as I cannot unlock the document, nor curate it?

> inception.jar[1647125]: 2021-07-15 16:13:40 WARN [admin] ListenerRequestHandler - behavior not enabled; ignore call. Behavior org.apache.wicket.ajax.markup.html.form.AjaxButton$1@50e60329 at component [LambdaAjaxButton [Component id = confirm]]

**Comment by reckart** [comment] 2021-07-15 06:34
Try clicking the "refresh" button on the monitoring page to see if that changes anything. Also see if there is any (error) message in the log when you do this.

**Comment by david-waterworth** [comment] 2021-07-15 06:46
I exported the document, deleted and then re-imported. This time I was able to lock it with no error but its still not able to be curated. I've tried refreshing etc. I can actually put it back editable though - I just didn't know how to use that feature.

**Comment by reckart** [comment] 2021-07-15 08:56
What happens if you left-click on the clipboard icon for your document in the "curation" column of the monitoring page?

On the first click, it should say that the document is state is changed to "curation finished" and when you click again, it should go to "curation in progress".

The query that retrieves the curatable documents is this:

https://github.com/inception-project/inception/blob/375bb44c4cc5c936d0d183ba75291dfe9b0bcf0a/inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/storage/CurationDocumentServiceImpl.java#L109-L136

If you can access the database (works best when using MariaDB/MySQL), you could have a peek at the `annotation_document` and `source_document` tables. Otherwise, you could export the entire project from the project settings pane and have a look at the source document and annotation document entires in the JSON "exportedprojectXXXX.json" file at the root of the ZIP.

**Comment by david-waterworth** [comment] 2021-07-15 22:14
Nothing happens, no matter what I do it always says "Curation state can only be changed once curation has started."

![image](https://user-images.githubusercontent.com/5028974/125864468-03d462b5-081f-4f9c-a4d1-cba247201948.png)


I cycled through the annotation states, the log entries are:

> Jul 16 08:05:06 home-ubuntu-ml inception.jar[1647125]: 2021-07-16 08:05:06 INFO [admin] ApplicationPageBase - admin: The state of document [jci-points.xmi] for user [admin] has been set to [IGNORE]
> Jul 16 08:05:09 home-ubuntu-ml inception.jar[1647125]: 2021-07-16 08:05:09 INFO [admin] ApplicationPageBase - admin: The state of document [jci-points.xmi] for user [admin] has been set to [INPROGRESS]
> Jul 16 08:05:11 home-ubuntu-ml inception.jar[1647125]: 2021-07-16 08:05:11 INFO [admin] ApplicationPageBase - admin: The state of document [jci-points.xmi] for user [admin] has been set to [FINISHED]

The same document appears in `source_documents` and `annotation_documents` (ie same name). 

>   "source_documents" : [ {
>     "name" : "jci-points.xmi",
>     "format" : "xmi",
>     "state" : "ANNOTATION_FINISHED",
>     "timestamp" : null,
>     "created" : 1626331331343,
>     "updated" : 1626386536753
>   } ],
>   "annotation_documents" : [ {
>     "name" : "jci-points.xmi",
>     "user" : "admin",
>     "state" : "FINISHED",
>     "timestamp" : 1626331339810,
>     "annotatorState" : "IN_PROGRESS",
>     "sentence_accessed" : 0,
>     "created" : 1626331339149,
>     "updated" : 1626386711452
>   } ],

**Comment by reckart** [comment] 2021-07-16 10:36
Hm, yes - if you cannot access the document on the curation page, then it won't go into "curation-in-progress" and so clicking on the curation column does not become available.

I have no idea why you do not see the document on the curation page. From what I see

* the "admin" user has the curator and annotator roles in your project
* the annotation document "jci-points.xmi" is marked as FINISHED

... so the document should become available. The only additional condition "adoc.document.trainingDocument = false" should have no effect - but just to make sure, I'm updating the DB to drop this column since we do not use it anymore.

See: https://github.com/inception-project/inception/issues/2486

**Comment by reckart** [comment] 2021-07-16 19:04
Does the "Whoops" page provide a stack trace?

**Comment by david-waterworth** [comment] 2021-07-16 23:52
No, I've not seen that again so it may been unrelated, or it may have somehow corrupted the database. 

I think the original Whoops is caused by clicking `Finish Document` and then pressing `Confirm` multiple times. It should probably be disabled on first click as it can take a while before the dialogue is dismissed (for longer documents). But I don't that's my problem (unless the first time I did it really messed up the database).

I tried adding a copy of the same document with a different name and the same thing happens. After the document is finished it also didn't appear in the curation queue (I didn't make any changes, simple opened the copy and clicked Finish Document once).

I'll try with a totally different document later and see if that produces the same result. And maybe a different project.

**Comment by reckart** [comment] 2021-07-18 17:00
Maybe you could try rc7? https://github.com/inception-project/inception/releases/tag/inception-0.20.0-rc-7

**Comment by reckart** [comment] 2021-07-21 21:02
@david-waterworth have you had a chance of trying rc7? If you export the project and import it again, do you have the same problem in the re-imported version? If yes, maybe it would be possible to share the project with me privately so I can investigate because currently I have no idea what might cause this problem of not being able to curate.

**Comment by david-waterworth** [comment] 2021-07-22 05:44
@reckart I tried both export and import, and upgrading to RC7 and neither helped. I can send you the export of the project. What's the best way to do that - it's not huge, 8.3 MB

**Comment by reckart** [comment] 2021-07-22 06:00
Maybe send a link via Google Drive or Dropbox or whatever similar service by mail or alternatively attach the project directly to the mail you send me.

**Comment by reckart** [comment] 2021-07-28 10:06
Thanks for the project. I imported it and accessed the curation page - the open dialog shows two documents as "annotation_finished". There are no additional documents in the project. I assume when you import, the two documents do not appear in the dialog on the annotation page?

**Comment by david-waterworth** [comment] 2021-07-28 10:12
Yea that’s correct - I have updated to the official release today though, I’ll try again with that version tomorrow

**Comment by david-waterworth** [comment] 2021-07-29 00:47
It's still doing it in 20.0, and for all projects - not just the one I sent you.

I'll update from using the embedded database to a proper DB and see if that helps.

**Comment by david-waterworth** [comment] 2021-07-29 02:33
Updated to MariaDB from the embedded database and recreated my project. I can now mark documents as finished and they appear in the list of documents for curation.

So I guess something messed up the DB but I have no idea what. If it's possible I can send you the old DB, but I guess it's probably not worth your time.

**Comment by reckart** [comment] 2021-07-29 05:58
Please keep the old DB around for the moment. I'll try if I can reproduce the problem locally with the embedded DB. There are many users out there using the embedded DB and I wouldn't want them to be unable to curate - so this needs to be looked into further.

**Comment by reckart** [comment] 2021-08-03 07:58
It is indeed a bug in relation to using the embedded DB. Thanks for bringing this up!

**Closed** 2021-08-03 11:13 UTC
Labels: 🐛Bug
