### ISSUE TITLE
Curation no longer works

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#2524] opened 2021-08-02 14:12 UTC
**Describe the bug**
I cannot open finished documents on the curation page.

**To Reproduce**
1. Have a document finished by the annotators
2. Click on Curation
3. There are no documents that can be opened for curation

**Expected behavior**
The finished document(s) should be offered for curation

**Please complete the following information:**
 - Version and build ID: 21.0-SNAPSHOT, should also check 20.0 for this problem
 - OS: Linux
 - Browser: Chrome

**Comment by reckart** [comment] 2021-08-02 14:15
Are you using MySQL/MariaDB or an embedded DB?

**Comment by UWinch** [comment] 2021-08-02 14:15
I'm using MariaDB

**Comment by reckart** [comment] 2021-08-02 14:17
Sounds like a duplicate of this report then: https://github.com/inception-project/inception/issues/2483

**Closed** 2021-08-03 08:17 UTC
Labels: Module: Curation, 🐛Bug
