### ISSUE TITLE
Unable to find type when creating a span annotation

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#2357] opened 2021-06-09 20:34 UTC
**Describe the bug**
Error attaching this container for rendering: [AttachedAnnotationListPanel [Component id = relationListContainer]]

**To Reproduce**

tbd (Kibana)

**Expected behavior**
No error

**Please complete the following information:**
 - Version and build ID: 0.19.6

```

Error attaching this container for rendering: [AttachedAnnotationListPanel [Component id = relationListContainer]]","stacktrace":"org.apache.wicket.WicketRuntimeException: Error attaching this container for rendering: [AttachedAnnotationListPanel [Component id = relationListContainer]]
    at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1753)
    at org.apache.wicket.Component.onBeforeRender(Component.java:3831)
...
    at java.base/java.lang.Thread.run(Thread.java:832)\nCaused by: java.lang.IllegalArgumentException: Undeclared type [webanno.custom.Test]. Available types: uima.cas.TOP\nuima.cas.Integer\nuima.cas.Float\nuima.cas.String\n…
    at org.apache.uima.fit.util.CasUtil.getType(CasUtil.java:141) ~[uimafit-core-3.2.0.jar!/:3.2.0]
 at de.tudarmstadt.ukp.clarin.webanno.api.annotation.adapter.SpanOverlapBehavior.onCreate(SpanOverlapBehavior.java:74) ~[inception-api-annotation-0.19.6.jar!/:?]
         at de.tudarmstadt.ukp.clarin.webanno.api.annotation.adapter.SpanAdapter.handle(SpanAdapter.java:109) ~[inception-api-annotation-0.19.6.jar!/:?]
         at de.tudarmstadt.ukp.clarin.webanno.api.annotation.adapter.SpanAdapter.add(SpanAdapter.java:101) ~[inception-api-annotation-0.19.6.jar!/:?]
         at de.tudarmstadt.ukp.clarin.webanno.ui.annotation.detail.AnnotationDetailEditorPanel.createNewSpanAnnotation(AnnotationDetailEditorPanel.java:438) ~[inception-ui-annotation-0.19.6.jar!/:?]
```

**Comment by reckart** [comment] 2021-06-09 21:46
I have no idea how to reproduce it. I believe it would require to get into a situation where a layer becomes available in the dropdown on the right side of the screen, but the CAS of the user has not yet been upgraded to contain the layer. 

I have tried:
* open document for annotation
* in a separate window, open the project settings and create a new layer
* in the first window, reload / annotate something to provide a right-sidebar reload
* ... but I didn't get the new layer to be displayed in the dropdown... only when I edited the preferences and saved, it triggered a full document reload and the dropdown appeared

**Comment by reckart** [comment] 2022-08-10 17:52
Closing because we still have no info on how to reproduce.

**Closed** 2022-08-10 17:53 UTC
Labels: 🐛Bug, 🚫 Invalid, Module: Annotation
