### ISSUE TITLE
Invalid UIMA CAS XMI XML 1.1

### ISSUE THREAD

**Issue by vishalmodagekar** [inception-project/inception#4153] opened 2023-08-21 17:33 UTC
**Describe the bug**
Annotated PDF giving exception when exported as UIMA CAS XMI (XML 1.0) "Export failed: SAXParseException: Trying to serialize non-XML 1.0 character: 0x1 at offset .."  but can be exported as UIMA CAS XMI (XML 1.1). However, this XML has invalid xmlChars. Not able to parse the XML file using python package 'dkpro-cassis' functionality 'load_cas_from_xmi'. Throwing exception 'XMLSyntaxError: xmlParseCharRef: invalid xmlChar value ..'. Attached is the exported xmi file and typesystem xml for reference.
[file-2_10.1177_0333102421989620.zip](https://github.com/inception-project/inception/files/12399126/file-2_10.1177_0333102421989620.zip)

**Comment by reckart** [comment] 2023-08-21 17:35
Try using v29.0.

**Comment by reckart** [comment] 2023-09-12 08:51
Assuming this was a duplicate of https://github.com/inception-project/inception/issues/4058 and v29 works.

**Closed by reckart** 2023-09-12 08:51 UTC
Labels: Support request
