### ISSUE TITLE
TSV annotations/curations cannot be uploaded

### ISSUE THREAD

**Issue by JavierLuna** [inception-project/inception#2119] opened 2021-03-21 20:43 UTC
**Describe the bug**
See https://github.com/Savanamed/pycaprio/issues/37.
Users cannot upload a TSV annotation or curation using the remote API, either using the swagger page or `pycaprio`.

I've reproduced the issue in my local setup and have investigated a bit further into the issue:
### If you use `pycaprio`
 It seems that for a single `create_annotation` request creates 5 different `upload*****.bin` files, 4 are empty and 1 of them contains the valid TSV file (file with the `715 bytes`):

```
root@840fee31bc96:/tmp/save# ls -la
total 16
drwxr-xr-x 2 root root 4096 Mar 21 20:16 .
drwxrwxrwt 1 root root 4096 Mar 21 20:16 ..
-rw-r--r-- 1 root root  715 Mar 21 20:16 upload11890889729257226988.bin <---- This one is ok
-rw-r--r-- 1 root root    0 Mar 21 20:16 upload13315753524840596911.bin
-rw-r--r-- 1 root root    0 Mar 21 20:16 upload15460114994601421348.bin
-rw-r--r-- 1 root root    0 Mar 21 20:16 upload18109373663279840799.bin
-rw-r--r-- 1 root root    0 Mar 21 20:16 upload2227545189505745283.bin
```

INCEpTION then tries to load an empty file:
```
inception_1  | 2021-03-21 20:16:03 INFO [remote] WebannoTsv1Reader - Scanning [file:/tmp/]
inception_1  | 2021-03-21 20:16:03 INFO [remote] WebannoTsv1Reader - Found [1] resources to be read
inception_1  | 2021-03-21 20:16:03 INFO [remote] WebannoTsv1Reader - 0 of 1: file:/tmp/upload2227545189505745283.bin
inception_1  | 2021-03-21 20:16:03 ERROR [remote] AeroRemoteApiController - The document appears to be empty. Unable to detect any tokens or sentences. Empty documents cannot be imported.
inception_1  | java.io.IOException: The document appears to be empty. Unable to detect any tokens or sentences. Empty documents cannot be imported.
```
### If you use the Swagger
This time the file upload only generates one `upload*****.bin` file with the correct content on it, but still fails loading it:

```
{
  "messages": [
    {
      "level": "ERROR",
      "message": "Internal server error: upload17772541904199074754.bin This is not a valid TSV File"
    }
  ]
}
```

**To Reproduce**
Steps to reproduce the behavior: See https://github.com/Savanamed/pycaprio/issues/37

**Expected behavior**
Both endpoints work. 

**Screenshots**
See https://github.com/Savanamed/pycaprio/issues/37

**Please complete the following information:**
 - Version and build ID: built from master of this repository, ran using docker
 - OS: Arch linux 5.11.2-arch1-1 kernel but again, INCEpTION runs on last stable docker version
 - Browser: Firefox, Brave (chrome based)

**Additional context**

I would also want some clarification on why `pycaprio` creates 5 files and if I messed up the multi-part upload somehow (weird as I use the same procedure when I upload documents and everything works fine).

**Comment by reckart** [comment] 2021-03-23 08:00
@JavierLuna thanks for the report. In the log, it looks like you try uploading a file in the deprecated WebAnno TSV 1 format (format ID `tsv`). For the current WebAnno 3.x version support, the file format ID needs to be set to `ctsv3`.

**Comment by reckart** [comment] 2021-04-18 16:40
Ok, so I'm trying to reproduce this with this code:

```
import os

from pycaprio.core.exceptions import InceptionBadResponse
from pycaprio.core.mappings import InceptionFormat
from pycaprio import Pycaprio

client = Pycaprio("http://localhost:8080/inception-app-webapp/", authentication=("admin", "admin"))

with open(os.path.join("some-document.tsv"), "rb") as annotation:
    try:
        client.api.create_curation(372, 43759, curation_format=InceptionFormat.TSV, content=annotation)
    except InceptionBadResponse as e:
        print(e.bad_response.content)
        raise e
```

What I get on the server logs is that first:

```
State [NEW] not valid when uploading a curation.
```

This error is apparently not thrown by pycaprio. Instead, it appears that pycaprio is re-trying the request several times due to:

**retryable_client.py**
```
    @retry(retry=retry_if_exception_type(RetryableException), stop=stop_after_attempt(MAX_RETRY_ATTEMPTS))
    def _request(self, method: str, url: str, allowed_statuses: Optional[status_list_type],
                 **kwargs) -> requests.Response:
```

However, in these retries, the payload is no longer submitted, so we get on the server these messages:

```
AeroRemoteApiController - Line does not start with expected prefix [#FORMAT=]: [null]
```

I'd say these retires are the reason for the empty files. Seems to be to be a bug in pycaprio.

**Comment by JavierLuna** [comment] 2021-04-26 18:27
Will work on the retryable client

**Comment by reckart** [comment] 2021-11-30 22:08
Assuming the that issue was resolved as there was no more feedback and thus closing the issue.

**Closed by reckart** 2021-11-30 22:08 UTC
Labels: Support request, Module: Remote API
