### ISSUE TITLE
Mask out already labeled documents

### ISSUE THREAD

**Issue by konstantinmiller** [inception-project/inception#1753] opened 2020-07-08 13:53 UTC
In a multi-user project, it seems that individual users receive documents to be labeled that are already labeled by other users. Is that intended behavior? And if yes, can it be turned of? So that documents that are already labeled by one user are not suggested for labeling to other users?

**Comment by UWinch** [comment] 2020-07-10 07:27
Hi, yes that is intended behaviour. Depending on you annotation project, you want several users to annotate the same document so you can get some insights where they agree or develop a final annotation result from several annotators' annotations, a gold standard.

At the moment, you can only assign specific documents to users by using the Monitoring Page (accessible for project managers from the dashboard). We are currently working on a more dynamic workload assignment, but have no release date for this feature yet.

For some ideas on how to manage document assignment, you might want to read this discussion [on the mailing list](https://groups.google.com/forum/#!topic/inception-users/HsU6CJK5zL8).

**Comment by jcklie** [comment] 2020-07-28 08:27
We are currently working on dynamic workload assignment where project managers can specify how many times a document needs to be annotated. Annotators then do not select documents, but are assigned. In your case that would be 1. We will keep you up to date once it is ready to try out.

**Comment by reckart** [comment] 2020-07-28 08:47
> So that documents that are already labeled by one user are not suggested for labeling to other users?

By "suggested" you mean that documents already labeled by one person should not appear in the "Open document" dialog of another person anymore - is that correct?

The new workload assignment functionality we are working does not make use of the "Open document" dialog. We plan it to work as follows:
- user opens the annotation page and automatically a document suitable for annotation is shown
- when the user marks this document as finished, another suitable document opens automatically
- once a document has been marked as finished, the user cannot go back to it (and obviously also not make any changes to it anymore)

Would such a workflow work for you?

**Comment by konstantinmiller** [comment] 2020-07-30 05:08
Sounds good! IMHO that's the best solution.

Cheers
Konstantin

--
To send me an encrypted email, download my public key from pgp.mit.edu

**Comment by reckart** [comment] 2021-02-21 09:22
There is a new experimental "dynamic workflow" management mode available since 0.18.0 which can be enabled by adding `workload.dynamic.enabled=true` to the settings.properties file. 

In this mode, you can configure how many users per document you want. The system automatically takes the users to the documents. There is no "open" dialog for the users in this mode and once they mark a document as finished, they cannot go back to it.

**Closed** 2021-02-21 09:22 UTC
Labels: Module: Workload, 🆕Enhancement
