### ISSUE TITLE
Annotation browser sometimes does not load in sidebar curation mode

### ISSUE THREAD

**Issue by s2fische** [inception-project/inception#4994] opened 2024-08-16 09:20 UTC
For a number of already annotated and curated documents, the list of annotations (selectable in left-hand side bar) does not load, even after several minutes of waiting, when opening them as a curator in annotation mode. This happens whether the curation is still in progress or not. All documents from our project except for three (one of which has not been annotated yet) are affected.

<img width="632" alt="Screenshot 2024-08-16 105027" src="https://github.com/user-attachments/assets/b7b31586-88d3-4cbb-a679-b86c15c44017">

How it should look:

<img width="629" alt="Screenshot 2024-08-16 111831" src="https://github.com/user-attachments/assets/a929fe7b-a69d-40d5-94e3-cdff79941d7d">

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 33.3 (2024-07-23 20:06:53, build d72b69e1)
 - OS: Windows 11
 - Browser: Chrome

**Comment by reckart** [comment] 2024-08-18 19:09
Could you please open the javascript developer console in your browser and check in the console log if you see any error(s) there?

**Comment by reckart** [comment] 2024-08-20 08:07
I think I can reproduce it.

```
AnnotationsByLabelList.svelte:211 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'offsets')
    at AnnotationsByLabelList.svelte:211:82
    at Array.sort (<anonymous>)
    at r.$$.update (AnnotationsByLabelList.svelte:211:82)
    at ks (scheduler.js:115:6)
    at At (scheduler.js:79:5)
```

**Comment by reckart** [comment] 2024-08-20 08:58
I suspect the problem occurs when a relation/link endpoint from a curator is hidden because an annotation at this point has already been merged. Probably in this case, a relation/link may still be rendered using the annotator-annotation as the endpoint instead of the curated annotation.

**Closed** 2024-08-20 19:52 UTC
Labels: 🐛Bug, Module: Annotation
