### ISSUE TITLE
Disagreement recorded if one of the annotators includes a comment even if the tags are the same

### ISSUE THREAD

**Issue by gsmolenska** [inception-project/inception#1290] opened 2019-07-09 12:42 UTC
**Describe the bug**
When the annotations are the same but one of the annotators includes a comment together with the tag, inception records it as disagreement. 
In the attached example, both annotators  chose the tag "MISSING_WORD" but one of them added a comment "de". The tags are marked blue as disagreement even though it shouldn't be recorded as an error.

**To Reproduce**

**Expected behavior**
If the annotators chose the same tag, it should be recorded as agreement despite any possible mismatch between the comments by the annotation.

**Screenshots**
The screenshots of the interface and the raw data are added.

**Please complete the following information:**
 - Version and build ID: INCEpTION 𝜶 -- 0.5.0 (2018-09-02 21:31:06, build 
<img width="1107" alt="Screenshot 2019-07-09 at 14 41 39" src="https://user-images.githubusercontent.com/39188650/60888705-bdb32700-a257-11e9-98be-8b51262b5028.png">

 - OS: macOS Mojave
 - Browser: Safari

**Additional context**

**Comment by reckart** [comment] 2019-07-09 12:59
At the moment, the system cannot distinguish between "meaningful" features and "comment" features. 

I think what you are asking for is an option to exclude certain features of a layer from agreement/curation calculation - is that right?

**Comment by gresmol** [comment] 2019-07-09 13:23
Yes, that is correct! I would like the comments to be disregarded from the agreement/curation calculation.

**Comment by reckart** [comment] 2019-07-10 10:09
I am thinking about which of the following two approaches would be better:
* introduce a new flag at the level of the feature configuration in the project settings to exclude/include a feature from the comparison
* using the existing `visible` flag which determines if the value of a given feature is included in the annotation label

I think that a comment feature should normally have `visible` set to `false` such that potentially longish comments do not show up in the annotation label. 

@gresmol what do you think? Would it be ok for you to set `visible` to `false` or and we change the code to exclude invisible labels from the comparison? Is it important for you to have the comment be visible as part of the annotation label? Or would you otherwise think it would be better to separate the visibility of a feature value in the label and using it for comparison by having two different flags?

**Comment by gresmol** [comment] 2019-07-10 13:40
Setting visible to false and changing the code to exclude invisible labels from the comparison would work very well!

**Comment by reckart** [comment] 2019-07-10 13:51
@UWinch @jcklie do you have any opinions on this?

**Comment by reckart** [comment] 2022-04-09 16:19
Duplicate of #2495 - Ignorable features for curation mode. Option to exclude features such as comments from curation exists since 21.0.1.

**Closed by reckart** 2022-04-09 16:19 UTC
Labels: 🆕Enhancement, Requires upstream changes, Module: Curation
