### ISSUE TITLE
Double clicking on recommended annotations doesn't hide them

### ISSUE THREAD

**Issue by qiuwei** [inception-project/inception#889] opened 2019-01-21 11:14 UTC
**Describe the bug**
According to the documentation, double-click should reject a recommendation. However, in the latest 0.7.0 version, it doesn't hide the rejected annotations automatically without a browser refresh.  

**To Reproduce**
configure some recommenders and try annotating a few documents. 

**Please complete the following information:**
 - Version and build ID: INCEpTION -- 0.7.0 (2019-01-13 23:29:04, build 2a706c9e60e52474b5d60975fd4d13e0cbb64178
 - OS: [e.g., Linux Cent OS]
 - Browser: both chrome and safari

**Additional context**
If I recall it correctly, it seems to be a regression. I didn't experience this in previous 0.6.8 version.

**Comment by reckart** [comment] 2019-01-21 11:52
Closing as duplicate of https://github.com/inception-project/inception/issues/859

We expect 0.7.1 to be released in the next few days.

**Closed** 2019-01-21 11:52 UTC
Labels: 🎭Duplicate
