### ISSUE TITLE
Repeated hits at search

### ISSUE THREAD

**Issue by Petitcriu** [inception-project/inception#3667] opened 2022-12-29 10:47 UTC
### Describe the bug

I am getting repeated results at search when I'm searching on the surface form (Token) as well as on the annotated layers. My latest search for a very rare word form at token level gives 165 hits, with only 3 actual hits repeated 55 times.

### Expected behavior

I just want to get the hits once.

### Screenshots

![grafik](https://user-images.githubusercontent.com/120732546/209940259-1d47b8bf-6543-4f46-a24d-d7f75eccf96b.png)

### Environment

Version and build ID: see bottom of the INCEpTION browser screen
Operating system: e.g. Windows, Linux, OS X
Browser: e.g. Chrome, Safari, Firefox, ...
INCEpTION 23.7, build ID 8dec45b3
Windows 10
Firefox

### Additional context

I have an instance from Ruhr-Universität Bochum.

**Comment by reckart** [comment] 2022-12-29 10:48
I'll see if I can reproduce it locally.

**Comment by reckart** [comment] 2022-12-29 10:51
So simply going to one of my projects and trying, I cannot reproduce it - no duplicates.

Can you please try re-indexing the data? Depending on which version you are using, the re-index button should be either in the options dropdown of the search sidebar on the annotation page or in the "annotation" section of the project settings.

**Comment by reckart** [comment] 2023-01-04 22:04
Seems to be a duplicate of https://github.com/inception-project/inception/issues/3662

**Comment by reckart** [comment] 2023-01-17 18:35
@Petitcriu have you tried rebuilding the indexes? If it fixed the problem, did the problem come back again after a while or does it remain fixed?

**Comment by reckart** [comment] 2024-04-15 19:58
Closing as I could not reproduce it and there has been no additional feedback.

**Closed by reckart** 2024-04-15 19:58 UTC
Labels: 🐛Bug, Module: Project Search, Needs confirmation
