### ISSUE TITLE
Problem running INCEPTION in WINDOWS 10

### ISSUE THREAD

**Issue by rentehaee** [inception-project/inception#4983] opened 2024-08-10 13:33 UTC
hello everyone
I downloaded the latest version of INCEPTION and ran it by clicking the JAR file and also running it from the command line in WINDOWS 10. The program is executed and its running message is displayed. But I get the following message in the browser:

This localhost page can’t be foundNo webpage was found for the web address: http://localhost:8080/login.html
HTTP ERROR 404

The steps in command line is attached in this txt file:
[error-inception.txt](https://github.com/user-attachments/files/16569720/error-inception.txt)

**Please guide me to solve the problem.**
thanks 
Alireza Entehaee

**Comment by reckart** [comment] 2024-08-12 16:59
I'm afraid, I cannot reproduce the problem. I tried on my machine with macos and also just tried with Adoptium Temurin 21.0.4+7LTS on Windows 10 both running via the command line prompt as well as double-clicking on the JAR. I'm afraid, I cannot reproduce the issue.

Just a wild guess, but are you possible running a non-western locale? If so, might it be possible to check if switching to a western locale resolves the problem?

**Comment by reckart** [comment] 2024-08-23 15:36
That's great. If you by chance figure out what is causing the problem with your user profile, please comment here.

For the time being though, I will close the issue. Happy to re-open if/when we get more information on how to reproduce it.

**Closed by reckart** 2024-08-23 15:36 UTC
Labels: 🐛Bug, Needs confirmation
