### ISSUE TITLE
User documents view disappear on curation page

### ISSUE THREAD

**Issue by UWinch** [inception-project/inception#1794] opened 2020-08-06 13:16 UTC
**Describe the bug**
On the curation page when part of the page is re-loaded, the views showing the users' annotations are not shown.

**To Reproduce**
1. Open a document on the curation page
2. Cause a partial re-load e.g. by changing the number of displayed rows or re-merging the annotations
3. See that the users' documents are no longer shown, can be retrieved by reloading the page

**Expected behavior**
Should not disappear.

**Screenshots**
![curation-missing-views](https://user-images.githubusercontent.com/29500351/89536121-b4e4aa00-d7f7-11ea-8c30-a7bb34c7fc97.png)

**Please complete the following information:**
 - Version and build ID: 0.17.0-SNAPSHOT
 - OS: Ubuntu
 - Browser: Chrome

**Comment by mbugert** [comment] 2020-08-06 14:19
Oh yes, this one! I never managed to reproduce it... looking forward to seeing it fixed :blush:.

**Comment by UWinch** [comment] 2020-08-13 09:06
@reckart I think this has to do with this webanno PR https://github.com/webanno/webanno/pull/1704. I found that the views are loaded again when I use ` deferredRendering = true;` instead of `false` in the `BratVisualizer.render(AjaxRequest aTarget)` method:

```
public void render(AjaxRequestTarget aTarget)
    {
        LOG.debug("[{}][{}] render", getMarkupId(), vis.getMarkupId());
        
        // Controls whether rendering should happen within the AJAX request or after the AJAX
        // request. Doing it within the request has the benefit of the browser only having to
        // recalculate the layout once at the end of the AJAX request (at least theoretically)
        // while deferring the rendering causes the AJAX request to complete faster, but then
        // the browser needs to recalculate its layout twice - once of any Wicket components
        // being re-rendered and once for the brat view to re-render.
        final boolean deferredRendering = false;

        StringBuilder js = new StringBuilder();
        
        if (deferredRendering) {
            js.append("setTimeout(function() {");
        }
        
        js.append(bratRenderCommand(getDocumentData()));
        
        if (deferredRendering) {
            js.append("}, 0);");
        }
        
        aTarget.appendJavaScript(js);
    }
```

However, I'm not sure if this change messes up your render performance improvement again. I also don't really understand why this would help, shouldn't the rendering happen at the end of the ajax request anyway because we are using the `AjaxComponentRespondListener` to wait with the rendering? Do you have thoughts on this?

**Comment by reckart** [comment] 2020-08-13 12:08
E.g. in this method in **de.tudarmstadt.ukp.clarin.webanno.api.annotation.preferences.PreferencesActionBarItem**:

```
    private void actionCompletePreferencesChange(AjaxRequestTarget aTarget)
    {
        page.actionLoadDocument(aTarget);
    }
```

try changing it to

```
    private void actionCompletePreferencesChange(AjaxRequestTarget aTarget)
    {
        page.actionLoadDocument(null);
    }
```

and see if that works.

**Comment by UWinch** [comment] 2020-08-13 16:44
Thanks for the idea. It partly helps, the user docs are shown again on the curation page. However, now changing the preferences on the annotation page no longer updates the page and we cannot update the sidebar size on the curation page. 

I'll compare the refresh and load process of the two pages, maybe I'll have another idea.

**Comment by reckart** [comment] 2020-08-13 16:46
Strange. Passing on `null` here should actually perform a more radical page refresh.

**Comment by reckart** [comment] 2020-08-13 16:56
Are you running with the Wicket development mode enabled? Do you also see messages like this in the Wicket AJAX debug console?

```
ERROR: Wicket.Ajax.Call.processEvaluation: Exception evaluating javascript: TypeError: null is not an object (evaluating 'Wicket.$('vis223').dispatcher'), text: (function(){Wicket.Ajax.ajax({"u":"./curation.html?13-2.0-centerArea-actionBar-items-0-item-showPreviousDocument&p=19","c":"showPreviousDocument24c","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?13-2.0-centerArea-actionBar-items-0-item-showNextDocument&p=19","c":"showNextDocument24d","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?13-2.0-centerArea-actionBar-items-0-item-showOpenDocumentDialog&p=19","c":"showOpenDocumentDialog24e","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?13-2.0-centerArea-actionBar-items-0-item-showExportDialog&p=19","c":"showExportDialog24f","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?13-2.0-centerArea-actionBar-items-1-item-form-gotoPageLink&p=19","m":"POST","c":"gotoPageLink251","f":"form250","sc":"gotoPageLink","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?13-2.0-centerArea-actionBar-items-1-item-form-showNext&p=19","c":"showNext252","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?13-2.0-centerArea-actionBar-items-1-item-form-showPrevious&p=19","c":"showPrevious253","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?13-2.0-centerArea-actionBar-items-1-item-form-showFirst&p=19","c":"showFirst254","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?13-2.0-centerArea-actionBar-items-1-item-form-showLast&p=19","c":"showLast255","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?13-2.0-centerArea-actionBar-items-2-item-toggleScriptDirection&p=19","c":"toggleScriptDirection256","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?13-2.0-centerArea-actionBar-items-3-item-showFinishDocumentDialog&p=19","c":"showFinishDocumentDialog257","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?13-2.0-centerArea-actionBar-items-3-item-showResetDocumentDialog&p=19","c":"showResetDocumentDialog258","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?13-2.0-centerArea-actionBar-items-4-item-showPreferencesDialog&p=19","c":"showPreferencesDialog259","e":"click"});})();(function(){jQuery('#root174').menu({ "select": function (event,ui) {
var attrs = {"u":"./curation.html?13-2.0-centerArea-suggestionViewPanel-contextMenu&p=19","c":"contextMenu196"};
var params = [{"name":"hash","value":ui.item[0].id}];
attrs.ep = params.concat(attrs.ep || []);
Wicket.Ajax.ajax(attrs);
}
```

**Comment by UWinch** [comment] 2020-08-14 09:12
Without any changes I got some errors like this:

```
Wicket.Ajax.Call.processEvaluation: Exception evaluating javascript: TypeError: Cannot read property 'dispatcher' of null, text: (function(){Wicket.Ajax.ajax({"u":"./curation.html?6-1.0-centerArea-actionBar-items-0-item-showPreviousDocument&p=44","c":"showPreviousDocument23a","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?6-1.0-centerArea-actionBar-items-0-item-showNextDocument&p=44","c":"showNextDocument23b","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?6-1.0-centerArea-actionBar-items-0-item-showOpenDocumentDialog&p=44","c":"showOpenDocumentDialog23c","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?6-1.0-centerArea-actionBar-items-0-item-showExportDialog&p=44","c":"showExportDialog23d","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?6-1.0-centerArea-actionBar-items-1-item-form-gotoPageLink&p=44","m":"POST","c":"gotoPageLink23f","f":"form23e","sc":"gotoPageLink","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?6-1.0-centerArea-actionBar-items-1-item-form-showNext&p=44","c":"showNext240","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?6-1.0-centerArea-actionBar-items-1-item-form-showPrevious&p=44","c":"showPrevious241","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?6-1.0-centerArea-actionBar-items-1-item-form-showFirst&p=44","c":"showFirst242","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?6-1.0-centerArea-actionBar-items-1-item-form-showLast&p=44","c":"showLast243","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?6-1.0-centerArea-actionBar-items-2-item-toggleScriptDirection&p=44","c":"toggleScriptDirection244","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?6-1.0-centerArea-actionBar-items-3-item-showFinishDocumentDialog&p=44","c":"showFinishDocumentDialog245","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?6-1.0-centerArea-actionBar-items-3-item-showResetDocumentDialog&p=44","c":"showResetDocumentDialog246","e":"click"});})();(function(){Wicket.Ajax.ajax({"u":"./curation.html?6-1.0-centerArea-actionBar-items-4-item-showPreferencesDialog&p=44","c":"showPreferencesDialog247","e":"click"});})();(function(){jQuery('#root41').menu({ "select": function (event,ui) {
var attrs = {"u":"./curation.html?6-1.0-centerArea-suggestionViewPanel-contextMenu&p=44","c":"contextMenu63"};
var params = [{"name":"hash","value":ui.item[0].id}];
attrs.ep = params.concat(attrs.ep || []);
Wicket.Ajax.ajax(attrs);
}
 });})();
...
```

I think at this point we no longer have the BratVisualizations with a certain ID, because the user views are re-loaded. So, calls like `Wicket.$('vis188')` (where `vis188` is the markupId that changes every time) are null.

**Comment by reckart** [comment] 2020-08-14 09:23
That would probably be the reason why stuff doesn't render. Mind that even if the element with that ID is there, if it was re-rendered as part of an AJAX refresh, it may have lost the brat properties that were attached to it, e.g. the `dispatcher` property. In that case, it would be necessary to re-initialize brat on that element again.

I believe we have two options:

* maybe high effort, fast rendering: render the annotator data list view only when the page is fully reloaded and otherwise do not re-render the list view, just trigger a rendering of each of the annotator views
* naive: when re-rendering the list view, ensure that the brat views are always completely reinitialized.

I don't remember the exact details of the annotator data list view on the curation page off the top of my head, so that's all the quick guidance I can give atm. E.g. I do not know atm under which conditions the list view is re-rendered.

**Comment by reckart** [comment] 2020-09-06 11:09
Upstream fix merged.

**Closed by reckart** 2020-09-06 11:09 UTC
Labels: Module: Curation, Requires upstream changes, 🐛Bug
