### ISSUE TITLE
Use Spring Boot to load plugin jars on boot

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1209] opened 2019-05-27 14:27 UTC
**Is your feature request related to a problem? Please describe.**
It would be nice if one could put jars next to INCEpTION which are loaded on boot, e.g. for plugins.

**Describe the solution you'd like**
Use the `PropertiesLauncher` of Spring Boot and specify a folder whose jar contents are loaded at boot.

https://docs.spring.io/spring-boot/docs/current/reference/html/executable-jar.html#executable-jar-property-launcher-features

**Describe alternatives you've considered**
Wait for someone to implement a plugin server and use a real plugin system.

**Comment by jcklie** [comment] 2019-05-27 14:30
I tried the following:

1) Build `inception-example-imls-data-majority` and copy the jar to /tmp/plugins
2) Remove `inception-example-imls-data-majority` module the from the app-webapp pom
3) Build the standalone jar and copy it to /tmp
4) Run `java -jar inception-app-standalone-0.10.0-SNAPSHOT.jar org.springframework.boot.loader.PropertiesLauncher -Dloader.path=file:plugins/ -Dloader.debug=true`

This did not work, maybe we need Spring boot 2

**Comment by reckart** [comment] 2019-06-08 22:56
Closing as duplicate of #1240 (and maybe #1243).

**Closed by reckart** 2019-06-08 22:56 UTC
Labels: Scalability, 🆕Enhancement
