### ISSUE TITLE
Curation mode merging

### ISSUE THREAD

**Issue by s2fische** [inception-project/inception#4822] opened 2024-05-22 16:10 UTC
**Describe the bug**
We have noticed that in several instances, when entering curation mode, completely corresponding annotations (from different annotators) are not merged automatically, as they should be, even though this has worked previously.

Another problem we noticed is very long loading times (maybe 10-15 seconds) after selecting/clicking on an annotation (from an annotator) to be added into curation that only happen sometimes, seemingly without any discernible reason.

**Expected behavior**
Curation mode should merge any annotations that correspond completely (i.e. they should appear at the top of the screen as well, not just in the windows showing the different annotators' versions).

**Screenshots**
<img width="782" alt="Screenshot 2024-05-22 175329" src="https://github.com/inception-project/inception/assets/170112224/779d5215-7771-4e64-9e19-bc16d806e815">

**Please complete the following information:**
 - Version and build ID: 31.3 (2024-03-12 20:11:22, build 6743f93)
 - OS: Windows 10
 - Browser: Chrome

**Comment by reckart** [comment] 2024-05-22 16:14
Please upgrade to 32.2 and see if the issue persists. If it does, it would be great i you could provide a demo project export that contains a document which allows me to reproduce the issue. You can also send me the demo project by email if you do not want to publicly attach it here.

**Comment by reckart** [comment] 2024-06-15 11:14
@bgittel @s2fische Thank you for providing data to investigate. Since we could both no longer reproduce the issue, I am closing this now as cannot-reproduce. If the problem re-appears, please comment or open another issue.

**Closed by reckart** 2024-06-15 11:14 UTC
Labels: 🐛Bug, Module: Curation
