### ISSUE TITLE
Allow Changing Annotation Boundaries from Edit Annotation

### ISSUE THREAD

**Issue by giuliabaldini** [inception-project/inception#3723] opened 2023-01-12 12:39 UTC
Hi there,

I am not sure whether this feature already exists and I have not found it, or if there is another way to obtain the same results.

**Is your feature request related to a problem? Please describe.**
It would be nice, if we could change the boundaries of an annotation (beginning and end) within the annotation editor and not by removing an annotation and adding it again. 

**Describe the solution you'd like**
<img width="396" alt="image" src="https://user-images.githubusercontent.com/44327645/212067570-da9d1490-88f7-40a5-9630-3b24277d16d5.png">
For example, in the picture above, we would like to have a "begin" and "end" field that can be modified and change the length of the annotation.

**Describe alternatives you've considered**
Deleting and recreating the annotation has the same effect.

Best,
Giulia @karzideh

**Comment by reckart** [comment] 2023-01-12 13:11
Feature is coming in the next major release: https://github.com/inception-project/inception/issues/283


https://user-images.githubusercontent.com/1410238/212075130-1f85b00b-30aa-4321-b220-33237b6e829e.mp4

**Comment by reckart** [comment] 2023-01-17 18:48
Duplicate of https://github.com/inception-project/inception/issues/283

**Closed by reckart** 2023-01-17 18:48 UTC
