### ISSUE TITLE
Function of show merged annotations checkbox difficult to understand

### ISSUE THREAD

**Issue by s2fische** [inception-project/inception#4851] opened 2024-06-05 15:40 UTC
The annotations (relations) of one specific annotator (Melanie) were not displayed when only her annotations were selected (on the left). They only emerged when "show merged annotations" was selected as well, which is an error because the second annotator did not have the exact same annotations so they couldn't have been merged.

![2 Clipboard - 5  Juni 2024 16_54](https://github.com/inception-project/inception/assets/170112224/67ca995a-f061-4666-ab5f-12a0738beaab)

![2 Clipboard - 5  Juni 2024 16_55](https://github.com/inception-project/inception/assets/170112224/6ee4f5a1-2224-4ff3-8c02-fdafb7a05a43)

**Please complete the following information:**
- Version and build ID: 32.2 (2024-05-14 20:46:45, build https://github.com/inception-project/inception/commit/101ef65398d5a2152bed7855559a1753d4c0750d)
- OS: Windows 10
- Browser: Chrome

**Comment by reckart** [comment] 2024-06-05 15:42
The annotations from Melanie are hidden because the curator has a matching annotation already merged into the curation CAS. If you enable "show merged annotations" you turn this hiding off.

**Comment by s2fische** [comment] 2024-06-12 11:37
But the relation tief-oberflächlich-Opposition has not already been merged by the curation user, both of them are relations annotated by Melanie. The same thing happened with other relations and in other documents as well.

Maybe it has something to do with the fact that the entities the relations are connected to have already been merged because of other annotations?

**Comment by reckart** [comment] 2024-06-12 19:29
Ok, I think I understand the problem now. I believe the issue is that the relations connect to the "Hollenstein: eine Tür | GRENZE" Annotation which has not been merged - and thus the relations are not drawn.

**Comment by reckart** [comment] 2024-06-13 18:31
So it is kind of expected behavior I guess...

https://github.com/inception-project/inception/assets/1410238/17b6521b-955c-4476-a1d8-a07183b94e4f

The system detects that the relations exist between the endpoints 'b' and 'c'. If any of these endpoints has not been merged, then the relation between them is considered to no longer be relevant. 

I understand that in your case, you would like to be able to merge an endpoint that does not connect to a relation but then still be able to merge the relation that did connect to the other endpoint that you did not merge? Or am I misunderstanding?

**Comment by s2fische** [comment] 2024-07-09 16:12
The problem isn't merging itself but that some of Melanie's annotations (relations and entities) aren't displayed at all unless "show merged annotations" has been selected. Our guess is that those relations which connect to start/end points that have not been merged yet aren't displayed.

<img width="488" alt="Screenshot 2024-07-09 181110" src="https://github.com/inception-project/inception/assets/170112224/78870a73-c12e-4c5e-b148-735c998e82a4">


It seems that version 33.1 has not solved the problem yet, see new screenshot.

**Comment by reckart** [comment] 2024-07-19 13:59
So it turns out the main issue here is probably that the label of the **Show merged annotations** checkbox is misleading. It should be changed to something like **Show all annotations** or something like that.

**Closed** 2024-07-20 01:43 UTC
Labels: 🐛Bug, Module: Curation
