### ISSUE TITLE
Annotation doesn't work for some string features

### ISSUE THREAD

**Issue by llaska** [inception-project/inception#1912] opened 2020-12-29 13:58 UTC
When selecting or typing a tag for any of two of the features "Sorts-and-Roles" or "Refers-to", nothing happens. There is no error message. The other string features, some with cyrillic, some with latin tags, work fine.

There is nothing in the log.

No such problems with versions 0.17.0 and 0.17.1 

A short recording here: https://drive.google.com/file/d/1mgjCV-wUoKHcUzMkdNjM3y5VOifHc3fC/view?usp=sharing.

 - Version and build ID:  0.17.2 (2020-12-05 12:16:10, build a464ec626b3c672805649dde69a0d8b7eb671612) 
 - OS: Ubuntu 18.04.5 LTS
 - Browser: Firefox, Safari, Edge, Chrome

**Log excerpt**
2020-12-28 08:00:11 INFO [Laska] DocumentServiceImpl - Created annotation document [8674] for user [Laska] for source document [DobriVojnikovIBTC.txt](1267) in project [IBSCT-Shemes](36)
2020-12-28 08:00:12 INFO [Laska] AnnotationSchemaServiceImpl - Upgraded CAS of user [Laska] for document [DobriVojnikovIBTC.txt](1267) in project [IBSCT-Shemes](36)
2020-12-28 08:01:30 INFO [Laska] ImportExportServiceImpl - Exported annotations [DobriVojnikovIBTC.txt](1267) for user [Laska] from project [IBSCT-Shemes](36) using format [ctsv3]
2020-12-28 08:05:10 INFO [Laska] ApplicationPageBase - Laska: The [BG] annotation has been deleted.
2020-12-28 08:20:29 INFO [Laska] ApplicationPageBase - Laska: The [BG] annotation has been deleted.
2020-12-28 08:23:22 INFO [Laska] ApplicationPageBase - Laska: The [BG] annotation has been deleted.
2020-12-28 08:23:25 INFO [Laska] ApplicationPageBase - Laska: The [BG] annotation has been deleted.

**Comment by reckart** [comment] 2020-12-29 14:11
I am pretty sure this is a duplicate of https://github.com/inception-project/inception/issues/1897 - which is already fixed but not released yet.

**Comment by llaska** [comment] 2020-12-29 14:25
That's great then! Apologies for the duplication.

**Comment by reckart** [comment] 2020-12-29 14:31
No worries. It tells us we should really prioritize the bug fix release...

**Comment by reckart** [comment] 2020-12-29 18:42
Ok, release 0.17.3 is out - fingers crossed...

**Closed** 2020-12-29 18:42 UTC
Labels: Module: Annotation, 🐛Bug

**Comment by llaska** [comment] 2020-12-29 19:15
Yay! Just tested it, works just fine :)
Thanks!

Il giorno mar 29 dic 2020 alle ore 20:42 Richard Eckart de Castilho <
notifications@github.com> ha scritto:
